# LOO summary table (DEG 200)

Builds a NeurIPS-ready summary table from `results/loo_summary_deg_200.csv`.

- Aggregates across seeds and held-out cell types (mean ± std).
- Bolds the best performer per metric (direction-aware).
- Renames `baseline` to `mean shift`.
- Annotates columns with ↑ (higher is better) or ↓ (lower is better).

In [41]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [42]:
import pandas as pd
from pathlib import Path

In [43]:
DATASET_NAME = "merfish"
N_DEG = 50
CSV_PATH = f"../results/loo_summary_{DATASET_NAME}_DEG_{N_DEG}_v2.csv"
OUT_DIR = Path("../results")
OUT_DIR.mkdir(exist_ok=True)

df = pd.read_csv(CSV_PATH, engine="python")
df.head()

,sid,model_name,holdout_celltype,n_deg,spearman,pearson,precision,direction_match,direction_match_k,direction_match_gt,mixing_index,edistance_global,edistance_local,edistance_pca,edistance_pca_log,rmse,mse_lfc,nb_deviance
0,C57BL6J-2.036,baseline,GABAergic neuron_Fiber_tracts,50,0.570374,0.608349,0.00,0.0,0.00,0.08,0.665761,35.923476,37.855664,1312.361304,23.686294,605.263245,373.183899,2.828218
1,C57BL6J-2.036,baseline,GABAergic neuron_Isocortex,50,0.670297,0.648808,0.16,1.0,0.16,0.60,0.675934,43.577318,47.911228,931.079596,24.102474,1496.381836,128.245697,2.299169
2,C57BL6J-2.036,baseline,astrocyte_Fiber_tracts,50,0.382818,0.415556,0.10,1.0,0.10,0.82,0.126393,32.656474,32.247583,1008.780884,13.687747,1876.262451,112.146637,1.535210
3,C57BL6J-2.036,baseline,astrocyte_Isocortex,50,0.735864,0.676738,0.24,1.0,0.24,0.86,0.009123,60.410183,62.203837,1795.630774,30.873113,3056.416260,113.270416,4.212565
4,C57BL6J-2.036,baseline,endothelial cell_Fiber_tracts,50,0.498319,0.576818,0.06,1.0,0.06,0.86,0.055016,37.047877,37.398380,1343.643640,17.327092,1701.265381,140.084076,3.201076

In [44]:
# Rename holdout_celltype by replacing the last '_' in with '-'
if DATASET_NAME == "merfish":
    df["holdout_celltype"] = df["holdout_celltype"].str.replace("Fiber_tracts", "Fiber-tracts", regex=False)
else:
    df["holdout_celltype"] = df["holdout_celltype"].str.replace("T_cell", "T-cell", regex=False)

In [45]:
# Split holdout_celltype on '_' and place everything in [0] as holdout_celltype, and everything in [1:] as perturbation
df["perturbation"] = df["holdout_celltype"].apply(lambda x: "".join(x.split("_")[-1]) if len(x.split("_")) > 1 else "")
df["holdout_celltype"] = df["holdout_celltype"].apply(lambda x: "-".join(x.split("_")[:-1]))
df

,sid,model_name,holdout_celltype,n_deg,spearman,pearson,precision,direction_match,direction_match_k,direction_match_gt,mixing_index,edistance_global,edistance_local,edistance_pca,edistance_pca_log,rmse,mse_lfc,nb_deviance,perturbation
0,C57BL6J-2.036,baseline,GABAergic neuron,50,0.570374,0.608349,0.00,0.0,0.00,0.08,0.665761,35.923476,37.855664,1312.361304,23.686294,605.263245,373.183899,2.828218,Fiber-tracts
1,C57BL6J-2.036,baseline,GABAergic neuron,50,0.670297,0.648808,0.16,1.0,0.16,0.60,0.675934,43.577318,47.911228,931.079596,24.102474,1496.381836,128.245697,2.299169,Isocortex
2,C57BL6J-2.036,baseline,astrocyte,50,0.382818,0.415556,0.10,1.0,0.10,0.82,0.126393,32.656474,32.247583,1008.780884,13.687747,1876.262451,112.146637,1.535210,Fiber-tracts
3,C57BL6J-2.036,baseline,astrocyte,50,0.735864,0.676738,0.24,1.0,0.24,0.86,0.009123,60.410183,62.203837,1795.630774,30.873113,3056.416260,113.270416,4.212565,Isocortex
4,C57BL6J-2.036,baseline,endothelial cell,50,0.498319,0.576818,0.06,1.0,0.06,0.86,0.055016,37.047877,37.398380,1343.643640,17.327092,1701.265381,140.084076,3.201076,Fiber-tracts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,C57BL6J-2.041,spatialprop-pert,astrocyte,50,0.638703,0.697145,0.02,1.0,0.02,0.84,0.996187,49.303682,55.555466,794.872485,27.981246,2654.451700,42.840770,4.916897,Fiber-tracts
322,C57BL6J-2.041,spatialprop-pert,oligodendrocyte,50,0.380456,0.720950,0.04,1.0,0.04,1.00,0.154696,51.094802,57.077675,763.452368,26.425109,1123.453900,77.272385,8.260915,Isocortex
323,C57BL6J-2.041,spatialprop-pert,oligodendrocyte,50,0.291621,0.546871,0.02,1.0,0.02,0.76,0.031325,60.957348,66.080022,971.256683,27.553000,7102.740000,40.809776,5.324323,Fiber-tracts
324,C57BL6J-2.041,spatialprop-pert,endothelial cell,50,0.727827,0.850666,0.02,1.0,0.02,0.98,0.017746,47.168227,54.013367,644.278601,25.942026,2184.035200,98.258170,7.386983,Isocortex
325,C57BL6J-2.041,spatialprop-pert,endothelial cell,50,0.411573,0.839520,0.08,1.0,0.08,0.94,0.996979,47.262965,53.773891,610.489172,25.954533,625.236400,145.910610,6.752406,Fiber-tracts

In [46]:
# Apply log10 on rmse
import numpy as np
df['rmse'] = np.log10(df['rmse'])

In [47]:
# Apply square root to mse_lfc
df['rmse_lfc'] = np.sqrt(df['mse_lfc'])

In [48]:
#df = df[df["model_name"] != "cellina-gat-pert"]

In [ ]:
# Metrics we want in the table and whether higher (+1) or lower (-1) is better.
METRICS = {
    #"spearman": +1,
    "pearson": +1,
    "direction_match_k": +1,
    #"edistance_global": -1,
    "edistance_pca_log": -1,
    #"rmse": -1,
    "rmse_lfc": -1,
    #"avg_rank": -1,
    #"nb_deviance": -1,
}

PRETTY_METRIC = {
    #"spearman": r"Spearman $\uparrow$",
    "pearson": r"Pearson $\uparrow$",
    "direction_match_k": r"Signed Precision $\uparrow$",
    #"edistance_global": r"E-dist (global) $\downarrow$",
    "edistance_pca_log": r"E-distance $\downarrow$",
    #"rmse": r"RMSE\textsubscript{counts} $\downarrow$",
    "rmse_lfc": r"RMSE\textsubscript{LFC} $\downarrow$",
    #"avg_rank": r"Avg. Rank $\downarrow$",
    #"nb_deviance": r"NB Deviance $\downarrow$",
}

# Model display order + renaming (baseline -> mean shift).
MODEL_RENAME = {
    "baseline": "mean shift",
    "cpa": "CPA",
    "scgen": "scGen",
    "mintflow": "MintFlow",
    "concert": "CONCERT",
    "cellina-ablated": "Cellina (ablated)",
    "cellina-graph": "Cellina-GAT",
    "cellina": "Cellina",
    "cellina-pert": r"Cellina$_{node-pert}$",
    "cellina-gat-pert": r"Cellina-GAT$_{node-pert}$",
    "spatialprop-pert": r"SpatialProp$_{node-pert}$"
}
MODEL_ORDER = [
    "mean shift",
    "CPA",
    "scGen",
    "MintFlow",
    "CONCERT",
    "Cellina (ablated)",
    "Cellina",
    "Cellina-GAT",
    r"Cellina$_{node-pert}$",
    r"Cellina-GAT$_{node-pert}$",
    r"SpatialProp$_{node-pert}$",
]

df["model_name"] = df["model_name"].map(lambda x: MODEL_RENAME.get(x, x))
df["model_name"].unique()

array(['mean shift', 'Cellina', 'Cellina (ablated)', 'Cellina-GAT',
       'CONCERT', 'CPA', 'scGen', 'MintFlow', 'Cellina$_{node-pert}$',
       'Cellina-GAT$_{node-pert}$', 'SpatialProp$_{node-pert}$'],
      dtype=object)

In [50]:
# Two-step aggregation:
#   1) within each slide, average over held-out cell types
#   2) across slides, compute mean ± std
agg = (
    df.groupby(["perturbation", "model_name"])[list(METRICS)]
    .agg(["mean", "std"])
)

# Ensure a consistent model order within each perturbation. Build a
# MultiIndex with (perturbation, model) in the desired display order and
# reindex the aggregated table to that index.
perturbations = list(df["perturbation"].dropna().unique())
# keep stable ordering; treat empty string as its own group if present
if any(p == "" for p in perturbations):
    perturbations = sorted(perturbations, key=lambda x: (x != "", x))
else:
    perturbations = sorted(perturbations)

desired_index = pd.MultiIndex.from_product(
    [perturbations, MODEL_ORDER], names=["perturbation", "model_name"]
)
agg = agg.reindex(desired_index)
agg

                                         pearson           direction_match_k  \
                                            mean       std              mean
perturbation model_name
Fiber-tracts mean shift                 0.314326  0.257209          0.049333
             CPA                        0.803148  0.147905          0.330667
             scGen                      0.724297  0.187134          0.141333
             MintFlow                   0.778977  0.181720          0.206667
             CONCERT                    0.760777  0.157922          0.134667
             Cellina (ablated)          0.772784  0.150121          0.246667
             Cellina                    0.806163  0.148556          0.378667
             Cellina-GAT                0.786653  0.150733          0.350000
             Cellina$_{node-pert}$      0.800821  0.143632          0.392000
             Cellina-GAT$_{node-pert}$  0.805532  0.153820          0.374286
             SpatialProp$_{node-pert}$  0.611576  0.198392          0.048000
Isocortex    mean shift                 0.543262  0.200259          0.198667
             CPA                        0.838500  0.169947          0.554667
             scGen                      0.823424  0.139806          0.257333
             MintFlow                   0.836147  0.164167          0.369333
             CONCERT                    0.785535  0.169921          0.234667
             Cellina (ablated)          0.822943  0.150016          0.456000
             Cellina                    0.851913  0.163727          0.568000
             Cellina-GAT                0.861504  0.137770          0.547143
             Cellina$_{node-pert}$      0.847482  0.167769          0.538667
             Cellina-GAT$_{node-pert}$  0.880761  0.134078          0.570000
             SpatialProp$_{node-pert}$  0.706052  0.078148          0.037333

                                                 edistance_pca_log            \
                                             std              mean       std
perturbation model_name
Fiber-tracts mean shift                 0.046517         21.292606  5.510431
             CPA                        0.130026          6.702401  2.480430
             scGen                      0.098116          5.280773  4.437667
             MintFlow                   0.161717         19.946036  1.644157
             CONCERT                    0.110961         24.227100  1.528090
             Cellina (ablated)          0.118723          8.313241  3.790866
             Cellina                    0.162387          8.098759  1.399171
             Cellina-GAT                0.174135          8.911058  3.505423
             Cellina$_{node-pert}$      0.187891          9.281117  1.993390
             Cellina-GAT$_{node-pert}$  0.173547          8.361566  2.387555
             SpatialProp$_{node-pert}$  0.051158         31.116636  5.619934
Isocortex    mean shift                 0.136165         29.072858  3.987335
             CPA                        0.132334          6.347754  1.506763
             scGen                      0.176128          6.174409  5.232605
             MintFlow                   0.158180         19.099524  1.969003
             CONCERT                    0.180391         25.598729  2.638171
             Cellina (ablated)          0.172743          9.197335  6.285590
             Cellina                    0.147900          7.821105  1.277504
             Cellina-GAT                0.130468         10.705607  4.759425
             Cellina$_{node-pert}$      0.126822          8.869321  1.693974
             Cellina-GAT$_{node-pert}$  0.100995          8.405367  2.179196
             SpatialProp$_{node-pert}$  0.023745         30.454819  4.736158

                                         rmse_lfc           nb_deviance  \
                                             mean       std        mean
perturbation model_name
Fiber-tracts mean shift                 11.709350  3.644510    2.435177
             CPA                         7.583705  5.802169    0.050038
             scGen                       7.443309  5.020947    0.315713
             MintFlow                    8.499556  6.591326    2.464844
             CONCERT                     8.548661  6.096233    0.171071
             Cellina (ablated)           7.979388  5.527233    0.078166
             Cellina                     7.489124  5.923910    0.041657
             Cellina-GAT                 7.956104  5.756003    0.073078
             Cellina$_{node-pert}$       7.462109  5.868877    0.041056
             Cellina-GAT$_{node-pert}$   7.738061  5.985631    0.048520
             SpatialProp$_{node-pert}$   8.022801  1.872516    8.693665
Isocortex    mean shift                 10.252531  1.916671    3.116649
             CPA                         5.139238  3.625469    0.055210
             scGen                       5.516599  2.922681    0.339926
             MintFlow                    6.043053  4.263296    2.407109
             CONCERT                     6.356479  3.892001    0.213913
             Cellina (ablated)           5.726455  3.457214    0.088674
             Cellina                     5.046322  3.700398    0.044486
             Cellina-GAT                 4.637579  2.510127    0.078947
             Cellina$_{node-pert}$       5.158502  3.663782    0.046824
             Cellina-GAT$_{node-pert}$   4.410997  2.399203    0.051758
             SpatialProp$_{node-pert}$   8.339942  2.225036   11.146741


                                             std
perturbation model_name
Fiber-tracts mean shift                 0.585296
             CPA                        0.039852
             scGen                      0.054018
             MintFlow                   0.924656
             CONCERT                    0.059333
             Cellina (ablated)          0.099204
             Cellina                    0.045775
             Cellina-GAT                0.093180
             Cellina$_{node-pert}$      0.054159
             Cellina-GAT$_{node-pert}$  0.048988
             SpatialProp$_{node-pert}$  4.788317
Isocortex    mean shift                 1.350899
             CPA                        0.041074
             scGen                      0.053258
             MintFlow                   0.743283
             CONCERT                    0.079546
             Cellina (ablated)          0.108471
             Cellina                    0.042426
             Cellina-GAT                0.103941
             Cellina$_{node-pert}$      0.039533
             Cellina-GAT$_{node-pert}$  0.051271
             SpatialProp$_{node-pert}$  5.931689

In [51]:
def find_best(agg: pd.DataFrame) -> dict:
    best = {}
    if isinstance(agg.index, pd.MultiIndex):
        # agg index: (perturbation, model_name)
        # collect perturbations preserving order
        raw = [p for p, _ in agg.index.tolist()]
        seen = set()
        perturbations = [p for p in raw if not (p in seen or seen.add(p))]
        for metric, direction in METRICS.items():
            for pert in perturbations:
                try:
                    means = agg.loc[pert][(metric, "mean")].dropna()
                except KeyError:
                    continue
                if means.empty:
                    continue
                best[(pert, metric)] = means.idxmax() if direction > 0 else means.idxmin()
    else:
        for metric, direction in METRICS.items():
            means = agg[(metric, "mean")].dropna()
            if means.empty:
                continue
            best[metric] = means.idxmax() if direction > 0 else means.idxmin()
    return best


def format_cell(mean, std, bold, na_str="--"):
    if pd.isna(mean):
        return na_str
    s = f"{mean:.2f} $\\pm$ {std:.2f}" if not pd.isna(std) else f"{mean:.2f}"
    return f"\\textbf{{{s}}}" if bold else s

In [52]:
best = find_best(agg)
table = pd.DataFrame(index=agg.index, columns=[PRETTY_METRIC[m] for m in METRICS])

for metric in METRICS:
    col = PRETTY_METRIC[metric]
    for model in agg.index:
        pert, model_name = model

        mean = agg.loc[model, (metric, "mean")]
        std = agg.loc[model, (metric, "std")]

        bold = (best.get((pert, metric)) == model_name)

        table.loc[model, col] = format_cell(mean, std, bold)
table

                                              Pearson $\uparrow$  \
perturbation model_name
Fiber-tracts mean shift                          0.31 $\pm$ 0.26
             CPA                                 0.80 $\pm$ 0.15
             scGen                               0.72 $\pm$ 0.19
             MintFlow                            0.78 $\pm$ 0.18
             CONCERT                             0.76 $\pm$ 0.16
             Cellina (ablated)                   0.77 $\pm$ 0.15
             Cellina                    \textbf{0.81 $\pm$ 0.15}
             Cellina-GAT                         0.79 $\pm$ 0.15
             Cellina$_{node-pert}$               0.80 $\pm$ 0.14
             Cellina-GAT$_{node-pert}$           0.81 $\pm$ 0.15
             SpatialProp$_{node-pert}$           0.61 $\pm$ 0.20
Isocortex    mean shift                          0.54 $\pm$ 0.20
             CPA                                 0.84 $\pm$ 0.17
             scGen                               0.82 $\pm$ 0.14
             MintFlow                            0.84 $\pm$ 0.16
             CONCERT                             0.79 $\pm$ 0.17
             Cellina (ablated)                   0.82 $\pm$ 0.15
             Cellina                             0.85 $\pm$ 0.16
             Cellina-GAT                         0.86 $\pm$ 0.14
             Cellina$_{node-pert}$               0.85 $\pm$ 0.17
             Cellina-GAT$_{node-pert}$  \textbf{0.88 $\pm$ 0.13}
             SpatialProp$_{node-pert}$           0.71 $\pm$ 0.08

                                       Signed Precision $\uparrow$  \
perturbation model_name
Fiber-tracts mean shift                            0.05 $\pm$ 0.05
             CPA                                   0.33 $\pm$ 0.13
             scGen                                 0.14 $\pm$ 0.10
             MintFlow                              0.21 $\pm$ 0.16
             CONCERT                               0.13 $\pm$ 0.11
             Cellina (ablated)                     0.25 $\pm$ 0.12
             Cellina                               0.38 $\pm$ 0.16
             Cellina-GAT                           0.35 $\pm$ 0.17
             Cellina$_{node-pert}$        \textbf{0.39 $\pm$ 0.19}
             Cellina-GAT$_{node-pert}$             0.37 $\pm$ 0.17
             SpatialProp$_{node-pert}$             0.05 $\pm$ 0.05
Isocortex    mean shift                            0.20 $\pm$ 0.14
             CPA                                   0.55 $\pm$ 0.13
             scGen                                 0.26 $\pm$ 0.18
             MintFlow                              0.37 $\pm$ 0.16
             CONCERT                               0.23 $\pm$ 0.18
             Cellina (ablated)                     0.46 $\pm$ 0.17
             Cellina                               0.57 $\pm$ 0.15
             Cellina-GAT                           0.55 $\pm$ 0.13
             Cellina$_{node-pert}$                 0.54 $\pm$ 0.13
             Cellina-GAT$_{node-pert}$    \textbf{0.57 $\pm$ 0.10}
             SpatialProp$_{node-pert}$             0.04 $\pm$ 0.02

                                         E-distance $\downarrow$  \
perturbation model_name
Fiber-tracts mean shift                         21.29 $\pm$ 5.51
             CPA                                 6.70 $\pm$ 2.48
             scGen                      \textbf{5.28 $\pm$ 4.44}
             MintFlow                           19.95 $\pm$ 1.64
             CONCERT                            24.23 $\pm$ 1.53
             Cellina (ablated)                   8.31 $\pm$ 3.79
             Cellina                             8.10 $\pm$ 1.40
             Cellina-GAT                         8.91 $\pm$ 3.51
             Cellina$_{node-pert}$               9.28 $\pm$ 1.99
             Cellina-GAT$_{node-pert}$           8.36 $\pm$ 2.39
             SpatialProp$_{node-pert}$          31.12 $\pm$ 5.62
Isocortex    mean shift                         29.07 $\pm$ 3.99
             CPA                                 6.35 $\pm$ 1.51
             scGen                      \textbf{6.17 $\pm$ 5.23}
             MintFlow                           19.10 $\pm$ 1.97
             CONCERT                            25.60 $\pm$ 2.64
             Cellina (ablated)                   9.20 $\pm$ 6.29
             Cellina                             7.82 $\pm$ 1.28
             Cellina-GAT                        10.71 $\pm$ 4.76
             Cellina$_{node-pert}$               8.87 $\pm$ 1.69
             Cellina-GAT$_{node-pert}$           8.41 $\pm$ 2.18
             SpatialProp$_{node-pert}$          30.45 $\pm$ 4.74

                                       RMSE\textsubscript{LFC} $\downarrow$  \
perturbation model_name
Fiber-tracts mean shift                                    11.71 $\pm$ 3.64
             CPA                                            7.58 $\pm$ 5.80
             scGen                                 \textbf{7.44 $\pm$ 5.02}
             MintFlow                                       8.50 $\pm$ 6.59
             CONCERT                                        8.55 $\pm$ 6.10
             Cellina (ablated)                              7.98 $\pm$ 5.53
             Cellina                                        7.49 $\pm$ 5.92
             Cellina-GAT                                    7.96 $\pm$ 5.76
             Cellina$_{node-pert}$                          7.46 $\pm$ 5.87
             Cellina-GAT$_{node-pert}$                      7.74 $\pm$ 5.99
             SpatialProp$_{node-pert}$                      8.02 $\pm$ 1.87
Isocortex    mean shift                                    10.25 $\pm$ 1.92
             CPA                                            5.14 $\pm$ 3.63
             scGen                                          5.52 $\pm$ 2.92
             MintFlow                                       6.04 $\pm$ 4.26
             CONCERT                                        6.36 $\pm$ 3.89
             Cellina (ablated)                              5.73 $\pm$ 3.46
             Cellina                                        5.05 $\pm$ 3.70
             Cellina-GAT                                    4.64 $\pm$ 2.51
             Cellina$_{node-pert}$                          5.16 $\pm$ 3.66
             Cellina-GAT$_{node-pert}$             \textbf{4.41 $\pm$ 2.40}
             SpatialProp$_{node-pert}$                      8.34 $\pm$ 2.23

                                        NB Deviance $\downarrow$
perturbation model_name
Fiber-tracts mean shift                          2.44 $\pm$ 0.59
             CPA                                 0.05 $\pm$ 0.04
             scGen                               0.32 $\pm$ 0.05
             MintFlow                            2.46 $\pm$ 0.92
             CONCERT                             0.17 $\pm$ 0.06
             Cellina (ablated)                   0.08 $\pm$ 0.10
             Cellina                             0.04 $\pm$ 0.05
             Cellina-GAT                         0.07 $\pm$ 0.09
             Cellina$_{node-pert}$      \textbf{0.04 $\pm$ 0.05}
             Cellina-GAT$_{node-pert}$           0.05 $\pm$ 0.05
             SpatialProp$_{node-pert}$           8.69 $\pm$ 4.79
Isocortex    mean shift                          3.12 $\pm$ 1.35
             CPA                                 0.06 $\pm$ 0.04
             scGen                               0.34 $\pm$ 0.05
             MintFlow                            2.41 $\pm$ 0.74
             CONCERT                             0.21 $\pm$ 0.08
             Cellina (ablated)                   0.09 $\pm$ 0.11
             Cellina                    \textbf{0.04 $\pm$ 0.04}
             Cellina-GAT                         0.08 $\pm$ 0.10
             Cellina$_{node-pert}$               0.05 $\pm$ 0.04
             Cellina-GAT$_{node-pert}$           0.05 $\pm$ 0.05
             SpatialProp$_{node-pert}$          11.15 $\pm$ 5.93

In [53]:
def insert_midrule_perts(latex, table):
    groups = table.index.get_level_values(0)
    boundaries = [i for i in range(1, len(groups)) if groups[i] != groups[i - 1]]

    lines = latex.splitlines()
    new_lines = []

    row_idx = 0

    for line in lines:
        new_lines.append(line)

        # detect data rows (skip header)
        if "&" in line and "\\\\" in line:
            if row_idx in boundaries:
                new_lines.append(r"\midrule")
            row_idx += 1

    latex = "\n".join(new_lines)
    return latex

In [54]:
is_multi_pert = table.index.get_level_values(0).nunique() > 1

if is_multi_pert:
    latex = table.to_latex(
        index_names=False, # removes the extra header row
        escape=False,
        header=False,
        column_format="ll" + "c" * table.shape[1],  # two index levels → 'll'
        multirow=True,  # for multiple perturbations
        caption=(
            f"Leave-one-celltype-out performance (top {N_DEG} DEGs). For each slide we "
            "first average over the held-out cell types, then report mean $\\pm$ std "
            f"across {df['sid'].nunique()} slides. Best per metric in \\textbf{{bold}}."
        ),
        label=f"tab:loo_summary_{DATASET_NAME}",
    )

    latex = latex.replace(r"\cline{1-7}", "")
    latex = latex.replace("\\begin{table}", "\\begin{table}[t]\n\\centering")
    latex = latex.replace(r"\multirow[t]", r"\multirow[c]")
    header = "Holdout \\\ perturbation & Method & " + " & ".join(table.columns) + r" \\"
    latex = latex.replace(
    "\\begin{tabular}{ll" + "c" * table.shape[1] + "}",
    "\\begin{tabular}{ll" + "c" * table.shape[1] + "}\n\\toprule\n" + header
    )
    latex = latex.replace(r"\midrule", "")
    latex = insert_midrule_perts(latex, table)
else:
    flat = table.reset_index(level=0, drop=True)

    latex = flat.to_latex(
        index=True,
        index_names=False,
        escape=False,
        column_format="l" + "c" * flat.shape[1],
        caption=(
            f"Leave-one-celltype-out performance (top {N_DEG} DEGs). "
            "Mean $\\pm$ std across slides. Best per metric in \\textbf{bold}."
        ),
        label=f"tab:loo_summary_{DATASET_NAME}",
    )
    latex = latex.replace("\\begin{table}", "\\begin{table}[t]\n\\centering")

print(latex)

(OUT_DIR / f"loo_summary_{DATASET_NAME}_DEG_{N_DEG}_table.tex").write_text(latex)

\begin{table}[t]
\centering
\caption{Leave-one-celltype-out performance (top 50 DEGs). For each slide we first average over the held-out cell types, then report mean $\pm$ std across 3 slides. Best per metric in \textbf{bold}.}
\label{tab:loo_summary_merfish}
\begin{tabular}{llccccc}
\toprule
Holdout \\ perturbation & Method & Pearson $\uparrow$ & Signed Precision $\uparrow$ & E-distance $\downarrow$ & RMSE\textsubscript{LFC} $\downarrow$ & NB Deviance $\downarrow$ \\
\toprule

\multirow[c]{11}{*}{Fiber-tracts} & mean shift & 0.31 $\pm$ 0.26 & 0.05 $\pm$ 0.05 & 21.29 $\pm$ 5.51 & 11.71 $\pm$ 3.64 & 2.44 $\pm$ 0.59 \\
 & CPA & 0.80 $\pm$ 0.15 & 0.33 $\pm$ 0.13 & 6.70 $\pm$ 2.48 & 7.58 $\pm$ 5.80 & 0.05 $\pm$ 0.04 \\
 & scGen & 0.72 $\pm$ 0.19 & 0.14 $\pm$ 0.10 & \textbf{5.28 $\pm$ 4.44} & \textbf{7.44 $\pm$ 5.02} & 0.32 $\pm$ 0.05 \\
 & MintFlow & 0.78 $\pm$ 0.18 & 0.21 $\pm$ 0.16 & 19.95 $\pm$ 1.64 & 8.50 $\pm$ 6.59 & 2.46 $\pm$ 0.92 \\
 & CONCERT & 0.76 $\pm$ 0.16 & 0.13 $\pm$ 0.11 & 24.23 $\pm$ 1.53 & 8.55 $\pm$ 6.10 & 0.17 $\pm$ 0.06 \\
 & Cellina (ablated) & 0.77 $\pm$ 0.15 & 0.25 $\pm$ 0.12 & 8.31 $\pm$ 3.79 & 7.98 $\pm$ 5.53 & 0.08 $\pm$ 0.10 \\
 & Cellina & \textbf{0.81 $\pm$ 0.15} & 0.38 $\pm$ 0.16 & 8.10 $\pm$ 1.40 & 7.49 $\pm$ 5.92 & 0.04 $\pm$ 0.05 \\
 & Cellina-GAT & 0.79 $\pm$ 0.15 & 0.35 $\pm$ 0.17 & 8.91 $\pm$ 3.51 & 7.96 $\pm$ 5.76 & 0.07 $\pm$ 0.09 \\
 & Cellina$_{node-pert}$ & 0.80 $\pm$ 0.14 & \textbf{0.39 $\pm$ 0.19} & 9.28 $\pm$ 1.99 & 7.46 $\pm$ 5.87 & \textbf{0.04 $\pm$ 0.05} \\
 & Cellina-GAT$_{node-pert}$ & 0.81 $\pm$ 0.15 & 0.37 $\pm$ 0.17 & 8.36 $\pm$ 2.39 & 7.74 $\pm$ 5.99 & 0.05 $\pm$ 0.05 \\
 & SpatialProp$_{node-pert}$ & 0.61 $\pm$ 0.20 & 0.05 $\pm$ 0.05 & 31.12 $\pm$ 5.62 & 8.02 $\pm$ 1.87 & 8.69 $\pm$ 4.79 \\
\midrule

\multirow[c]{11}{*}{Isocortex} & mean shift & 0.54 $\pm$ 0.20 & 0.20 $\pm$ 0.14 & 29.07 $\pm$ 3.99 & 10.25 $\pm$ 1.92 & 3.12 $\pm$ 1.35 \\
 & CPA & 0.84 $\pm$ 0.17 & 0.55 $\pm$ 0.13 & 6.35 $\pm$ 1.51 & 5.14 $\pm$ 3.63 & 0.06 $\pm$ 0.04 \\
 & scGen & 0.82 $\pm$ 0.14 & 0.26 $\pm$ 0.18 & \textbf{6.17 $\pm$ 5.23} & 5.52 $\pm$ 2.92 & 0.34 $\pm$ 0.05 \\
 & MintFlow & 0.84 $\pm$ 0.16 & 0.37 $\pm$ 0.16 & 19.10 $\pm$ 1.97 & 6.04 $\pm$ 4.26 & 2.41 $\pm$ 0.74 \\
 & CONCERT & 0.79 $\pm$ 0.17 & 0.23 $\pm$ 0.18 & 25.60 $\pm$ 2.64 & 6.36 $\pm$ 3.89 & 0.21 $\pm$ 0.08 \\
 & Cellina (ablated) & 0.82 $\pm$ 0.15 & 0.46 $\pm$ 0.17 & 9.20 $\pm$ 6.29 & 5.73 $\pm$ 3.46 & 0.09 $\pm$ 0.11 \\
 & Cellina & 0.85 $\pm$ 0.16 & 0.57 $\pm$ 0.15 & 7.82 $\pm$ 1.28 & 5.05 $\pm$ 3.70 & \textbf{0.04 $\pm$ 0.04} \\
 & Cellina-GAT & 0.86 $\pm$ 0.14 & 0.55 $\pm$ 0.13 & 10.71 $\pm$ 4.76 & 4.64 $\pm$ 2.51 & 0.08 $\pm$ 0.10 \\
 & Cellina$_{node-pert}$ & 0.85 $\pm$ 0.17 & 0.54 $\pm$ 0.13 & 8.87 $\pm$ 1.69 & 5.16 $\pm$ 3.66 & 0.05 $\pm$ 0.04 \\
 & Cellina-GAT$_{node-pert}$ & \textbf{0.88 $\pm$ 0.13} & \textbf{0.57 $\pm$ 0.10} & 8.41 $\pm$ 2.18 & \textbf{4.41 $\pm$ 2.40} & 0.05 $\pm$ 0.05 \\
 & SpatialProp$_{node-pert}$ & 0.71 $\pm$ 0.08 & 0.04 $\pm$ 0.02 & 30.45 $\pm$ 4.74 & 8.34 $\pm$ 2.23 & 11.15 $\pm$ 5.93 \\

\bottomrule
\end{tabular}
\end{table}

3108

***

In [55]:
agg

                                         pearson           direction_match_k  \
                                            mean       std              mean
perturbation model_name
Fiber-tracts mean shift                 0.314326  0.257209          0.049333
             CPA                        0.803148  0.147905          0.330667
             scGen                      0.724297  0.187134          0.141333
             MintFlow                   0.778977  0.181720          0.206667
             CONCERT                    0.760777  0.157922          0.134667
             Cellina (ablated)          0.772784  0.150121          0.246667
             Cellina                    0.806163  0.148556          0.378667
             Cellina-GAT                0.786653  0.150733          0.350000
             Cellina$_{node-pert}$      0.800821  0.143632          0.392000
             Cellina-GAT$_{node-pert}$  0.805532  0.153820          0.374286
             SpatialProp$_{node-pert}$  0.611576  0.198392          0.048000
Isocortex    mean shift                 0.543262  0.200259          0.198667
             CPA                        0.838500  0.169947          0.554667
             scGen                      0.823424  0.139806          0.257333
             MintFlow                   0.836147  0.164167          0.369333
             CONCERT                    0.785535  0.169921          0.234667
             Cellina (ablated)          0.822943  0.150016          0.456000
             Cellina                    0.851913  0.163727          0.568000
             Cellina-GAT                0.861504  0.137770          0.547143
             Cellina$_{node-pert}$      0.847482  0.167769          0.538667
             Cellina-GAT$_{node-pert}$  0.880761  0.134078          0.570000
             SpatialProp$_{node-pert}$  0.706052  0.078148          0.037333

                                                 edistance_pca_log            \
                                             std              mean       std
perturbation model_name
Fiber-tracts mean shift                 0.046517         21.292606  5.510431
             CPA                        0.130026          6.702401  2.480430
             scGen                      0.098116          5.280773  4.437667
             MintFlow                   0.161717         19.946036  1.644157
             CONCERT                    0.110961         24.227100  1.528090
             Cellina (ablated)          0.118723          8.313241  3.790866
             Cellina                    0.162387          8.098759  1.399171
             Cellina-GAT                0.174135          8.911058  3.505423
             Cellina$_{node-pert}$      0.187891          9.281117  1.993390
             Cellina-GAT$_{node-pert}$  0.173547          8.361566  2.387555
             SpatialProp$_{node-pert}$  0.051158         31.116636  5.619934
Isocortex    mean shift                 0.136165         29.072858  3.987335
             CPA                        0.132334          6.347754  1.506763
             scGen                      0.176128          6.174409  5.232605
             MintFlow                   0.158180         19.099524  1.969003
             CONCERT                    0.180391         25.598729  2.638171
             Cellina (ablated)          0.172743          9.197335  6.285590
             Cellina                    0.147900          7.821105  1.277504
             Cellina-GAT                0.130468         10.705607  4.759425
             Cellina$_{node-pert}$      0.126822          8.869321  1.693974
             Cellina-GAT$_{node-pert}$  0.100995          8.405367  2.179196
             SpatialProp$_{node-pert}$  0.023745         30.454819  4.736158

                                         rmse_lfc           nb_deviance  \
                                             mean       std        mean
perturbation model_name
Fiber-tracts mean shift                 11.709350  3.644510    2.435177
             CPA                         7.583705  5.802169    0.050038
             scGen                       7.443309  5.020947    0.315713
             MintFlow                    8.499556  6.591326    2.464844
             CONCERT                     8.548661  6.096233    0.171071
             Cellina (ablated)           7.979388  5.527233    0.078166
             Cellina                     7.489124  5.923910    0.041657
             Cellina-GAT                 7.956104  5.756003    0.073078
             Cellina$_{node-pert}$       7.462109  5.868877    0.041056
             Cellina-GAT$_{node-pert}$   7.738061  5.985631    0.048520
             SpatialProp$_{node-pert}$   8.022801  1.872516    8.693665
Isocortex    mean shift                 10.252531  1.916671    3.116649
             CPA                         5.139238  3.625469    0.055210
             scGen                       5.516599  2.922681    0.339926
             MintFlow                    6.043053  4.263296    2.407109
             CONCERT                     6.356479  3.892001    0.213913
             Cellina (ablated)           5.726455  3.457214    0.088674
             Cellina                     5.046322  3.700398    0.044486
             Cellina-GAT                 4.637579  2.510127    0.078947
             Cellina$_{node-pert}$       5.158502  3.663782    0.046824
             Cellina-GAT$_{node-pert}$   4.410997  2.399203    0.051758
             SpatialProp$_{node-pert}$   8.339942  2.225036   11.146741


                                             std
perturbation model_name
Fiber-tracts mean shift                 0.585296
             CPA                        0.039852
             scGen                      0.054018
             MintFlow                   0.924656
             CONCERT                    0.059333
             Cellina (ablated)          0.099204
             Cellina                    0.045775
             Cellina-GAT                0.093180
             Cellina$_{node-pert}$      0.054159
             Cellina-GAT$_{node-pert}$  0.048988
             SpatialProp$_{node-pert}$  4.788317
Isocortex    mean shift                 1.350899
             CPA                        0.041074
             scGen                      0.053258
             MintFlow                   0.743283
             CONCERT                    0.079546
             Cellina (ablated)          0.108471
             Cellina                    0.042426
             Cellina-GAT                0.103941
             Cellina$_{node-pert}$      0.039533
             Cellina-GAT$_{node-pert}$  0.051271
             SpatialProp$_{node-pert}$  5.931689

In [56]:
df_avg = agg.groupby(level="model_name").mean()

In [57]:
df_avg = df_avg.loc[MODEL_ORDER]
df_avg

                            pearson           direction_match_k            \
                               mean       std              mean       std
model_name
mean shift                 0.428794  0.228734          0.124000  0.091341
CPA                        0.820824  0.158926          0.442667  0.131180
scGen                      0.773860  0.163470          0.199333  0.137122
MintFlow                   0.807562  0.172943          0.288000  0.159949
CONCERT                    0.773156  0.163922          0.184667  0.145676
Cellina (ablated)          0.797863  0.150068          0.351333  0.145733
Cellina                    0.829038  0.156142          0.473333  0.155143
Cellina-GAT                0.824078  0.144251          0.448571  0.152302
Cellina$_{node-pert}$      0.824152  0.155700          0.465333  0.157356
Cellina-GAT$_{node-pert}$  0.843146  0.143949          0.472143  0.137271
SpatialProp$_{node-pert}$  0.658814  0.138270          0.042667  0.037451

                          edistance_pca_log             rmse_lfc            \
                                       mean       std       mean       std
model_name
mean shift                        25.182732  4.748883  10.980941  2.780590
CPA                                6.525078  1.993597   6.361472  4.713819
scGen                              5.727591  4.835136   6.479954  3.971814
MintFlow                          19.522780  1.806580   7.271304  5.427311
CONCERT                           24.912915  2.083130   7.452570  4.994117
Cellina (ablated)                  8.755288  5.038228   6.852922  4.492223
Cellina                            7.959932  1.338337   6.267723  4.812154
Cellina-GAT                        9.808333  4.132424   6.296842  4.133065
Cellina$_{node-pert}$              9.075219  1.843682   6.310306  4.766330
Cellina-GAT$_{node-pert}$          8.383467  2.283376   6.074529  4.192417
SpatialProp$_{node-pert}$         30.785727  5.178046   8.181372  2.048776

                          nb_deviance
                                 mean       std
model_name
mean shift                   2.775913  0.968097
CPA                          0.052624  0.040463
scGen                        0.327819  0.053638
MintFlow                     2.435977  0.833969
CONCERT                      0.192492  0.069440
Cellina (ablated)            0.083420  0.103837
Cellina                      0.043071  0.044100
Cellina-GAT                  0.076012  0.098561
Cellina$_{node-pert}$        0.043940  0.046846
Cellina-GAT$_{node-pert}$    0.050139  0.050130
SpatialProp$_{node-pert}$    9.920203  5.360003

In [58]:
def find_best(agg: pd.DataFrame) -> dict:
    best = {}
    if isinstance(agg.index, pd.MultiIndex):
        # agg index: (perturbation, model_name)
        # collect perturbations preserving order
        raw = [p for p, _ in agg.index.tolist()]
        seen = set()
        perturbations = [p for p in raw if not (p in seen or seen.add(p))]
        for metric, direction in METRICS.items():
            for pert in perturbations:
                try:
                    means = agg.loc[pert][(metric, "mean")].dropna()
                except KeyError:
                    continue
                if means.empty:
                    continue
                best[(pert, metric)] = means.idxmax() if direction > 0 else means.idxmin()
    else:
        for metric, direction in METRICS.items():
            means = agg[(metric, "mean")].dropna()
            if means.empty:
                continue
            best[metric] = means.idxmax() if direction > 0 else means.idxmin()
    return best


def format_cell(mean, std, bold, na_str="--"):
    if pd.isna(mean):
        return na_str
    s = f"{mean:.2f} $\\pm$ {std:.2f}" if not pd.isna(std) else f"{mean:.2f}"
    return f"\\textbf{{{s}}}" if bold else s

In [59]:
best = find_best(df_avg)
table = pd.DataFrame(index=df_avg.index, columns=[PRETTY_METRIC[m] for m in METRICS])

for metric in METRICS:
    col = PRETTY_METRIC[metric]
    for model in df_avg.index:
        model_name = model

        mean = df_avg.loc[model, (metric, "mean")]
        std = df_avg.loc[model, (metric, "std")]

        bold = (best.get(metric) == model_name)

        table.loc[model, col] = format_cell(mean, std, bold)
table

,Pearson $\uparrow$,Signed Precision $\uparrow$,E-distance $\downarrow$,RMSE\textsubscript{LFC} $\downarrow$,NB Deviance $\downarrow$
model_name,,,,,
mean shift,0.43 $\pm$ 0.23,0.12 $\pm$ 0.09,25.18 $\pm$ 4.75,10.98 $\pm$ 2.78,2.78 $\pm$ 0.97
CPA,0.82 $\pm$ 0.16,0.44 $\pm$ 0.13,6.53 $\pm$ 1.99,6.36 $\pm$ 4.71,0.05 $\pm$ 0.04
scGen,0.77 $\pm$ 0.16,0.20 $\pm$ 0.14,\textbf{5.73 $\pm$ 4.84},6.48 $\pm$ 3.97,0.33 $\pm$ 0.05
MintFlow,0.81 $\pm$ 0.17,0.29 $\pm$ 0.16,19.52 $\pm$ 1.81,7.27 $\pm$ 5.43,2.44 $\pm$ 0.83
CONCERT,0.77 $\pm$ 0.16,0.18 $\pm$ 0.15,24.91 $\pm$ 2.08,7.45 $\pm$ 4.99,0.19 $\pm$ 0.07
Cellina (ablated),0.80 $\pm$ 0.15,0.35 $\pm$ 0.15,8.76 $\pm$ 5.04,6.85 $\pm$ 4.49,0.08 $\pm$ 0.10
Cellina,0.83 $\pm$ 0.16,\textbf{0.47 $\pm$ 0.16},7.96 $\pm$ 1.34,6.27 $\pm$ 4.81,\textbf{0.04 $\pm$ 0.04}
Cellina-GAT,0.82 $\pm$ 0.14,0.45 $\pm$ 0.15,9.81 $\pm$ 4.13,6.30 $\pm$ 4.13,0.08 $\pm$ 0.10
Cellina$_{node-pert}$,0.82 $\pm$ 0.16,0.47 $\pm$ 0.16,9.08 $\pm$ 1.84,6.31 $\pm$ 4.77,0.04 $\pm$ 0.05
Cellina-GAT$_{node-pert}$,\textbf{0.84 $\pm$ 0.14},0.47 $\pm$ 0.14,8.38 $\pm$ 2.28,\textbf{6.07 $\pm$ 4.19},0.05 $\pm$ 0.05
SpatialProp$_{node-pert}$,0.66 $\pm$ 0.14,0.04 $\pm$ 0.04,30.79 $\pm$ 5.18,8.18 $\pm$ 2.05,9.92 $\pm$ 5.36

In [60]:
flat = table.reset_index(level=0, drop=False)

latex = flat.to_latex(
    index=False,
    index_names=True,
    escape=False,
    column_format="l" + "c" * flat.shape[1],
    caption=(
        f"Leave-one-celltype-out performance (top {N_DEG} DEGs). "
        "Mean $\\pm$ std across slides. Best per metric in \\textbf{bold}."
    ),
    label=f"tab:loo_summary_{DATASET_NAME}",
)
latex = latex.replace("\\begin{table}", "\\begin{table}[t]\n\\centering")

print(latex)

(OUT_DIR / f"loo_summary_{DATASET_NAME}_DEG_{N_DEG}_table_avg.tex").write_text(latex)

\begin{table}[t]
\centering
\caption{Leave-one-celltype-out performance (top 50 DEGs). Mean $\pm$ std across slides. Best per metric in \textbf{bold}.}
\label{tab:loo_summary_merfish}
\begin{tabular}{lcccccc}
\toprule
model_name & Pearson $\uparrow$ & Signed Precision $\uparrow$ & E-distance $\downarrow$ & RMSE\textsubscript{LFC} $\downarrow$ & NB Deviance $\downarrow$ \\
\midrule
mean shift & 0.43 $\pm$ 0.23 & 0.12 $\pm$ 0.09 & 25.18 $\pm$ 4.75 & 10.98 $\pm$ 2.78 & 2.78 $\pm$ 0.97 \\
CPA & 0.82 $\pm$ 0.16 & 0.44 $\pm$ 0.13 & 6.53 $\pm$ 1.99 & 6.36 $\pm$ 4.71 & 0.05 $\pm$ 0.04 \\
scGen & 0.77 $\pm$ 0.16 & 0.20 $\pm$ 0.14 & \textbf{5.73 $\pm$ 4.84} & 6.48 $\pm$ 3.97 & 0.33 $\pm$ 0.05 \\
MintFlow & 0.81 $\pm$ 0.17 & 0.29 $\pm$ 0.16 & 19.52 $\pm$ 1.81 & 7.27 $\pm$ 5.43 & 2.44 $\pm$ 0.83 \\
CONCERT & 0.77 $\pm$ 0.16 & 0.18 $\pm$ 0.15 & 24.91 $\pm$ 2.08 & 7.45 $\pm$ 4.99 & 0.19 $\pm$ 0.07 \\
Cellina (ablated) & 0.80 $\pm$ 0.15 & 0.35 $\pm$ 0.15 & 8.76 $\pm$ 5.04 & 6.85 $\pm$ 4.49 & 0.08 $\pm$ 0.10 \\
Cellina & 0.83 $\pm$ 0.16 & \textbf{0.47 $\pm$ 0.16} & 7.96 $\pm$ 1.34 & 6.27 $\pm$ 4.81 & \textbf{0.04 $\pm$ 0.04} \\
Cellina-GAT & 0.82 $\pm$ 0.14 & 0.45 $\pm$ 0.15 & 9.81 $\pm$ 4.13 & 6.30 $\pm$ 4.13 & 0.08 $\pm$ 0.10 \\
Cellina$_{node-pert}$ & 0.82 $\pm$ 0.16 & 0.47 $\pm$ 0.16 & 9.08 $\pm$ 1.84 & 6.31 $\pm$ 4.77 & 0.04 $\pm$ 0.05 \\
Cellina-GAT$_{node-pert}$ & \textbf{0.84 $\pm$ 0.14} & 0.47 $\pm$ 0.14 & 8.38 $\pm$ 2.28 & \textbf{6.07 $\pm$ 4.19} & 0.05 $\pm$ 0.05 \\
SpatialProp$_{node-pert}$ & 0.66 $\pm$ 0.14 & 0.04 $\pm$ 0.04 & 30.79 $\pm$ 5.18 & 8.18 $\pm$ 2.05 & 9.92 $\pm$ 5.36 \\
\bottomrule
\end{tabular}
\end{table}

1645