# LOO summary table (DEG 200)

Builds a NeurIPS-ready summary table from `results/loo_summary_deg_200.csv`.

- Aggregates across seeds and held-out cell types (mean ± std).
- Bolds the best performer per metric (direction-aware).
- Renames `baseline` to `mean shift`.
- Annotates columns with ↑ (higher is better) or ↓ (lower is better).

In [18]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [19]:
import pandas as pd
from pathlib import Path

In [20]:
DATASET_NAME = "merfish"
N_DEG = 50
CSV_PATH = f"../results/loo_summary_{DATASET_NAME}_DEG_{N_DEG}_rebuttal.csv"
OUT_DIR = Path("../results")
OUT_DIR.mkdir(exist_ok=True)

df = pd.read_csv(CSV_PATH, engine="python")
df.head()

,sid,model_name,holdout_celltype,n_deg,spearman,pearson,precision,direction_match,direction_match_k,direction_match_gt,mixing_index,edistance_global,edistance_local,edistance_pca,edistance_pca_log,rmse,mse_lfc
0,C57BL6J-2.036,baseline,GABAergic neuron_Fiber_tracts,50,0.570374,0.608349,0.00,0.0,0.00,0.08,0.665761,36.035931,38.167051,1326.321997,23.548703,605.263245,373.183899
1,C57BL6J-2.036,baseline,GABAergic neuron_Isocortex,50,0.670297,0.648808,0.16,1.0,0.16,0.60,0.675934,43.563454,47.745749,916.233893,24.244977,1496.381836,128.245697
2,C57BL6J-2.036,baseline,astrocyte_Fiber_tracts,50,0.382818,0.415556,0.10,1.0,0.10,0.82,0.126393,32.461658,32.451422,1030.932532,13.411697,1876.262451,112.146637
3,C57BL6J-2.036,baseline,astrocyte_Isocortex,50,0.735864,0.676738,0.24,1.0,0.24,0.86,0.009123,60.480022,62.360514,1787.439282,30.966541,3056.416260,113.270416
4,C57BL6J-2.036,baseline,endothelial cell_Fiber_tracts,50,0.498319,0.576818,0.06,1.0,0.06,0.86,0.055016,36.975990,37.578715,1332.185315,17.214149,1701.265381,140.084076

In [21]:
# Rename holdout_celltype by replacing the last '_' in with '-'
if DATASET_NAME == "merfish":
    df["holdout_celltype"] = df["holdout_celltype"].str.replace("Fiber_tracts", "Fiber-tracts", regex=False)
else:
    df["holdout_celltype"] = df["holdout_celltype"].str.replace("T_cell", "T-cell", regex=False)

In [22]:
# Split holdout_celltype on '_' and place everything in [0] as holdout_celltype, and everything in [1:] as perturbation
df["perturbation"] = df["holdout_celltype"].apply(lambda x: "".join(x.split("_")[-1]) if len(x.split("_")) > 1 else "")
df["holdout_celltype"] = df["holdout_celltype"].apply(lambda x: "-".join(x.split("_")[:-1]))
df

,sid,model_name,holdout_celltype,n_deg,spearman,pearson,precision,direction_match,direction_match_k,direction_match_gt,mixing_index,edistance_global,edistance_local,edistance_pca,edistance_pca_log,rmse,mse_lfc,perturbation
0,C57BL6J-2.036,baseline,GABAergic neuron,50,0.570374,0.608349,0.00,0.0,0.00,0.08,0.665761,36.035931,38.167051,1326.321997,23.548703,605.263245,373.183899,Fiber-tracts
1,C57BL6J-2.036,baseline,GABAergic neuron,50,0.670297,0.648808,0.16,1.0,0.16,0.60,0.675934,43.563454,47.745749,916.233893,24.244977,1496.381836,128.245697,Isocortex
2,C57BL6J-2.036,baseline,astrocyte,50,0.382818,0.415556,0.10,1.0,0.10,0.82,0.126393,32.461658,32.451422,1030.932532,13.411697,1876.262451,112.146637,Fiber-tracts
3,C57BL6J-2.036,baseline,astrocyte,50,0.735864,0.676738,0.24,1.0,0.24,0.86,0.009123,60.480022,62.360514,1787.439282,30.966541,3056.416260,113.270416,Isocortex
4,C57BL6J-2.036,baseline,endothelial cell,50,0.498319,0.576818,0.06,1.0,0.06,0.86,0.055016,36.975990,37.578715,1332.185315,17.214149,1701.265381,140.084076,Fiber-tracts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,C57BL6J-2.041,spatialprop-pert,astrocyte,50,0.731669,0.758148,0.06,1.0,0.06,0.92,0.072450,38.204006,47.718252,401.915613,19.043097,2542.106700,33.687320,Fiber-tracts
322,C57BL6J-2.041,spatialprop-pert,oligodendrocyte,50,0.425018,0.640706,0.10,1.0,0.10,0.96,0.156538,54.967022,65.053135,492.834454,19.598421,1310.807400,127.696980,Isocortex
323,C57BL6J-2.041,spatialprop-pert,oligodendrocyte,50,0.285378,0.658684,0.04,1.0,0.04,0.84,0.050602,55.231331,65.077148,684.917322,27.405459,6247.942400,24.937560,Fiber-tracts
324,C57BL6J-2.041,spatialprop-pert,endothelial cell,50,0.794862,0.866290,0.28,1.0,0.28,0.98,0.012422,52.677394,60.332082,466.868317,20.071766,2591.789800,66.480200,Isocortex
325,C57BL6J-2.041,spatialprop-pert,endothelial cell,50,0.447107,0.862184,0.16,1.0,0.16,0.94,0.990937,42.077422,54.094219,479.218887,21.207024,918.444400,193.458020,Fiber-tracts

In [23]:
# Apply log10 on rmse
import numpy as np
df['rmse'] = np.log10(df['rmse'])

In [24]:
# Apply square root to mse_lfc
df['rmse_lfc'] = np.sqrt(df['mse_lfc'])

In [25]:
#df = df[df["model_name"] != "cellina-gat-pert"]

In [26]:
# Metrics we want in the table and whether higher (+1) or lower (-1) is better.
METRICS = {
    #"spearman": +1,
    "pearson": +1,
    "direction_match_k": +1,
    #"edistance_global": -1,
    "edistance_pca_log": -1,
    #"rmse": -1,
    "rmse_lfc": -1,
    #"avg_rank": -1,
}

PRETTY_METRIC = {
    #"spearman": r"Spearman $\uparrow$",
    "pearson": r"Pearson $\uparrow$",
    "direction_match_k": r"Signed Precision $\uparrow$",
    #"edistance_global": r"E-dist (global) $\downarrow$",
    "edistance_pca_log": r"E-distance $\downarrow$",
    #"rmse": r"RMSE\textsubscript{counts} $\downarrow$",
    "rmse_lfc": r"RMSE\textsubscript{LFC} $\downarrow$",
    #"avg_rank": r"Avg. Rank $\downarrow$",
}

# Model display order + renaming (baseline -> mean shift).
MODEL_RENAME = {
    "baseline": "mean shift",
    "cpa": "CPA",
    "scgen": "scGen",
    "mintflow": "MintFlow",
    "concert": "CONCERT",
    "cellina-ablated": "Cellina (ablated)",
    "cellina-graph": "Cellina-GAT",
    "cellina": "Cellina",
    "cellina-pert": r"Cellina$_{node-pert}$",
    "cellina-gat-pert": r"Cellina-GAT$_{node-pert}$",
    "spatialprop-pert": r"SpatialProp$_{node-pert}$"
}
MODEL_ORDER = [
    "mean shift",
    "CPA",
    "scGen",
    "MintFlow",
    "CONCERT",
    "Cellina (ablated)",
    "Cellina",
    "Cellina-GAT",
    r"Cellina$_{node-pert}$",
    r"Cellina-GAT$_{node-pert}$",
    r"SpatialProp$_{node-pert}$",
]

df["model_name"] = df["model_name"].map(lambda x: MODEL_RENAME.get(x, x))
df["model_name"].unique()

array(['mean shift', 'Cellina', 'Cellina (ablated)', 'Cellina-GAT',
       'CONCERT', 'CPA', 'scGen', 'MintFlow', 'Cellina-GAT$_{node-pert}$',
       'Cellina$_{node-pert}$', 'SpatialProp$_{node-pert}$'], dtype=object)

In [27]:
# Two-step aggregation:
#   1) within each slide, average over held-out cell types
#   2) across slides, compute mean ± std
agg = (
    df.groupby(["perturbation", "model_name"])[list(METRICS)]
    .agg(["mean", "std"])
)

# Ensure a consistent model order within each perturbation. Build a
# MultiIndex with (perturbation, model) in the desired display order and
# reindex the aggregated table to that index.
perturbations = list(df["perturbation"].dropna().unique())
# keep stable ordering; treat empty string as its own group if present
if any(p == "" for p in perturbations):
    perturbations = sorted(perturbations, key=lambda x: (x != "", x))
else:
    perturbations = sorted(perturbations)

desired_index = pd.MultiIndex.from_product(
    [perturbations, MODEL_ORDER], names=["perturbation", "model_name"]
)
agg = agg.reindex(desired_index)
agg

                                         pearson           direction_match_k  \
                                            mean       std              mean
perturbation model_name
Fiber-tracts mean shift                 0.314326  0.257209          0.049333
             CPA                        0.803148  0.147905          0.330667
             scGen                      0.724297  0.187134          0.141333
             MintFlow                   0.779929  0.179957          0.205333
             CONCERT                    0.760777  0.157922          0.134667
             Cellina (ablated)          0.765054  0.154527          0.270667
             Cellina                    0.806760  0.149349          0.385333
             Cellina-GAT                0.807745  0.157553          0.385714
             Cellina$_{node-pert}$      0.800862  0.143863          0.390667
             Cellina-GAT$_{node-pert}$  0.809068  0.157436          0.402857
             SpatialProp$_{node-pert}$  0.646903  0.180874          0.065333
Isocortex    mean shift                 0.543262  0.200259          0.198667
             CPA                        0.838500  0.169947          0.554667
             scGen                      0.823424  0.139806          0.257333
             MintFlow                   0.836694  0.164855          0.366667
             CONCERT                    0.785535  0.169921          0.234667
             Cellina (ablated)          0.812452  0.147851          0.461333
             Cellina                    0.855583  0.162216          0.568000
             Cellina-GAT                0.888099  0.146205          0.645714
             Cellina$_{node-pert}$      0.847937  0.166704          0.540000
             Cellina-GAT$_{node-pert}$  0.882053  0.147348          0.612857
             SpatialProp$_{node-pert}$  0.736170  0.095215          0.076000

                                                 edistance_pca_log            \
                                             std              mean       std
perturbation model_name
Fiber-tracts mean shift                 0.046517         21.318521  5.592233
             CPA                        0.130026          6.722707  2.511778
             scGen                      0.098116          5.174230  4.259160
             MintFlow                   0.162035         19.986863  1.493028
             CONCERT                    0.110961         24.265670  1.571847
             Cellina (ablated)          0.151727          8.267055  3.797852
             Cellina                    0.176225          8.085798  1.336926
             Cellina-GAT                0.177752          8.510647  1.968472
             Cellina$_{node-pert}$      0.181874          9.262618  1.970110
             Cellina-GAT$_{node-pert}$  0.179033          8.706483  1.962006
             SpatialProp$_{node-pert}$  0.069474         22.352469  3.985128
Isocortex    mean shift                 0.136165         28.991736  3.779707
             CPA                        0.132334          6.376609  1.525196
             scGen                      0.176128          6.128422  5.207939
             MintFlow                   0.161186         19.172766  1.963619
             CONCERT                    0.180391         25.616941  2.624898
             Cellina (ablated)          0.182282          9.639689  6.681962
             Cellina                    0.139345          7.731991  1.237993
             Cellina-GAT                0.112162          8.886133  1.014745
             Cellina$_{node-pert}$      0.126717          8.879079  1.748681
             Cellina-GAT$_{node-pert}$  0.110831          8.502168  0.899417
             SpatialProp$_{node-pert}$  0.065987         22.450624  2.325465

                                         rmse_lfc
                                             mean       std
perturbation model_name
Fiber-tracts mean shift                 11.709350  3.644510
             CPA                         7.583705  5.802169
             scGen                       7.443309  5.020947
             MintFlow                    8.469523  6.553852
             CONCERT                     8.548661  6.096233
             Cellina (ablated)           7.934244  5.548838
             Cellina                     7.379410  5.893500
             Cellina-GAT                 7.686689  6.175894
             Cellina$_{node-pert}$       7.464854  5.872045
             Cellina-GAT$_{node-pert}$   7.593340  6.202169
             SpatialProp$_{node-pert}$   7.439696  3.146678
Isocortex    mean shift                 10.252531  1.916671
             CPA                         5.139238  3.625469
             scGen                       5.516599  2.922681
             MintFlow                    6.006726  4.264789
             CONCERT                     6.356479  3.892001
             Cellina (ablated)           5.795062  3.411439
             Cellina                     4.999876  3.785554
             Cellina-GAT                 3.916522  2.820925
             Cellina$_{node-pert}$       5.160293  3.656519
             Cellina-GAT$_{node-pert}$   4.127175  2.651151
             SpatialProp$_{node-pert}$   6.432830  1.967418

In [11]:
def find_best(agg: pd.DataFrame) -> dict:
    best = {}
    if isinstance(agg.index, pd.MultiIndex):
        # agg index: (perturbation, model_name)
        # collect perturbations preserving order
        raw = [p for p, _ in agg.index.tolist()]
        seen = set()
        perturbations = [p for p in raw if not (p in seen or seen.add(p))]
        for metric, direction in METRICS.items():
            for pert in perturbations:
                try:
                    means = agg.loc[pert][(metric, "mean")].dropna()
                except KeyError:
                    continue
                if means.empty:
                    continue
                best[(pert, metric)] = means.idxmax() if direction > 0 else means.idxmin()
    else:
        for metric, direction in METRICS.items():
            means = agg[(metric, "mean")].dropna()
            if means.empty:
                continue
            best[metric] = means.idxmax() if direction > 0 else means.idxmin()
    return best


def format_cell(mean, std, bold, na_str="--"):
    if pd.isna(mean):
        return na_str
    s = f"{mean:.2f} $\\pm$ {std:.2f}" if not pd.isna(std) else f"{mean:.2f}"
    return f"\\textbf{{{s}}}" if bold else s

In [ ]:
best = find_best(agg)
table = pd.DataFrame(index=agg.index, columns=[PRETTY_METRIC[m] for m in METRICS])

for metric in METRICS:
    col = PRETTY_METRIC[metric]
    for model in agg.index:
        pert, model_name = model

        mean = agg.loc[model, (metric, "mean")]
        std = agg.loc[model, (metric, "std")]

        bold = (best.get((pert, metric)) == model_name)

        table.loc[model, col] = format_cell(mean, std, bold)
table

In [ ]:
def insert_midrule_perts(latex, table):
    groups = table.index.get_level_values(0)
    boundaries = [i for i in range(1, len(groups)) if groups[i] != groups[i - 1]]

    lines = latex.splitlines()
    new_lines = []

    row_idx = 0

    for line in lines:
        new_lines.append(line)

        # detect data rows (skip header)
        if "&" in line and "\\\\" in line:
            if row_idx in boundaries:
                new_lines.append(r"\midrule")
            row_idx += 1

    latex = "\n".join(new_lines)
    return latex

In [ ]:
is_multi_pert = table.index.get_level_values(0).nunique() > 1

if is_multi_pert:
    latex = table.to_latex(
        index_names=False, # removes the extra header row
        escape=False,
        header=False,
        column_format="ll" + "c" * table.shape[1],  # two index levels → 'll'
        multirow=True,  # for multiple perturbations
        caption=(
            f"Leave-one-celltype-out performance (top {N_DEG} DEGs). For each slide we "
            "first average over the held-out cell types, then report mean $\\pm$ std "
            f"across {df['sid'].nunique()} slides. Best per metric in \\textbf{{bold}}."
        ),
        label=f"tab:loo_summary_{DATASET_NAME}",
    )

    latex = latex.replace(r"\cline{1-7}", "")
    latex = latex.replace("\\begin{table}", "\\begin{table}[t]\n\\centering")
    latex = latex.replace(r"\multirow[t]", r"\multirow[c]")
    header = "Holdout \\\ perturbation & Method & " + " & ".join(table.columns) + r" \\"
    latex = latex.replace(
    "\\begin{tabular}{ll" + "c" * table.shape[1] + "}",
    "\\begin{tabular}{ll" + "c" * table.shape[1] + "}\n\\toprule\n" + header
    )
    latex = latex.replace(r"\midrule", "")
    latex = insert_midrule_perts(latex, table)
else:
    flat = table.reset_index(level=0, drop=True)

    latex = flat.to_latex(
        index=True,
        index_names=False,
        escape=False,
        column_format="l" + "c" * flat.shape[1],
        caption=(
            f"Leave-one-celltype-out performance (top {N_DEG} DEGs). "
            "Mean $\\pm$ std across slides. Best per metric in \\textbf{bold}."
        ),
        label=f"tab:loo_summary_{DATASET_NAME}",
    )
    latex = latex.replace("\\begin{table}", "\\begin{table}[t]\n\\centering")

print(latex)

(OUT_DIR / f"loo_summary_{DATASET_NAME}_DEG_{N_DEG}_table.tex").write_text(latex)

***

In [28]:
agg

                                         pearson           direction_match_k  \
                                            mean       std              mean
perturbation model_name
Fiber-tracts mean shift                 0.314326  0.257209          0.049333
             CPA                        0.803148  0.147905          0.330667
             scGen                      0.724297  0.187134          0.141333
             MintFlow                   0.779929  0.179957          0.205333
             CONCERT                    0.760777  0.157922          0.134667
             Cellina (ablated)          0.765054  0.154527          0.270667
             Cellina                    0.806760  0.149349          0.385333
             Cellina-GAT                0.807745  0.157553          0.385714
             Cellina$_{node-pert}$      0.800862  0.143863          0.390667
             Cellina-GAT$_{node-pert}$  0.809068  0.157436          0.402857
             SpatialProp$_{node-pert}$  0.646903  0.180874          0.065333
Isocortex    mean shift                 0.543262  0.200259          0.198667
             CPA                        0.838500  0.169947          0.554667
             scGen                      0.823424  0.139806          0.257333
             MintFlow                   0.836694  0.164855          0.366667
             CONCERT                    0.785535  0.169921          0.234667
             Cellina (ablated)          0.812452  0.147851          0.461333
             Cellina                    0.855583  0.162216          0.568000
             Cellina-GAT                0.888099  0.146205          0.645714
             Cellina$_{node-pert}$      0.847937  0.166704          0.540000
             Cellina-GAT$_{node-pert}$  0.882053  0.147348          0.612857
             SpatialProp$_{node-pert}$  0.736170  0.095215          0.076000

                                                 edistance_pca_log            \
                                             std              mean       std
perturbation model_name
Fiber-tracts mean shift                 0.046517         21.318521  5.592233
             CPA                        0.130026          6.722707  2.511778
             scGen                      0.098116          5.174230  4.259160
             MintFlow                   0.162035         19.986863  1.493028
             CONCERT                    0.110961         24.265670  1.571847
             Cellina (ablated)          0.151727          8.267055  3.797852
             Cellina                    0.176225          8.085798  1.336926
             Cellina-GAT                0.177752          8.510647  1.968472
             Cellina$_{node-pert}$      0.181874          9.262618  1.970110
             Cellina-GAT$_{node-pert}$  0.179033          8.706483  1.962006
             SpatialProp$_{node-pert}$  0.069474         22.352469  3.985128
Isocortex    mean shift                 0.136165         28.991736  3.779707
             CPA                        0.132334          6.376609  1.525196
             scGen                      0.176128          6.128422  5.207939
             MintFlow                   0.161186         19.172766  1.963619
             CONCERT                    0.180391         25.616941  2.624898
             Cellina (ablated)          0.182282          9.639689  6.681962
             Cellina                    0.139345          7.731991  1.237993
             Cellina-GAT                0.112162          8.886133  1.014745
             Cellina$_{node-pert}$      0.126717          8.879079  1.748681
             Cellina-GAT$_{node-pert}$  0.110831          8.502168  0.899417
             SpatialProp$_{node-pert}$  0.065987         22.450624  2.325465

                                         rmse_lfc
                                             mean       std
perturbation model_name
Fiber-tracts mean shift                 11.709350  3.644510
             CPA                         7.583705  5.802169
             scGen                       7.443309  5.020947
             MintFlow                    8.469523  6.553852
             CONCERT                     8.548661  6.096233
             Cellina (ablated)           7.934244  5.548838
             Cellina                     7.379410  5.893500
             Cellina-GAT                 7.686689  6.175894
             Cellina$_{node-pert}$       7.464854  5.872045
             Cellina-GAT$_{node-pert}$   7.593340  6.202169
             SpatialProp$_{node-pert}$   7.439696  3.146678
Isocortex    mean shift                 10.252531  1.916671
             CPA                         5.139238  3.625469
             scGen                       5.516599  2.922681
             MintFlow                    6.006726  4.264789
             CONCERT                     6.356479  3.892001
             Cellina (ablated)           5.795062  3.411439
             Cellina                     4.999876  3.785554
             Cellina-GAT                 3.916522  2.820925
             Cellina$_{node-pert}$       5.160293  3.656519
             Cellina-GAT$_{node-pert}$   4.127175  2.651151
             SpatialProp$_{node-pert}$   6.432830  1.967418

In [29]:
df_avg = agg.groupby(level="model_name").mean()

In [30]:
df_avg = df_avg.loc[MODEL_ORDER]
df_avg

                            pearson           direction_match_k            \
                               mean       std              mean       std
model_name
mean shift                 0.428794  0.228734          0.124000  0.091341
CPA                        0.820824  0.158926          0.442667  0.131180
scGen                      0.773860  0.163470          0.199333  0.137122
MintFlow                   0.808311  0.172406          0.286000  0.161610
CONCERT                    0.773156  0.163922          0.184667  0.145676
Cellina (ablated)          0.788753  0.151189          0.366000  0.167004
Cellina                    0.831171  0.155782          0.476667  0.157785
Cellina-GAT                0.847922  0.151879          0.515714  0.144957
Cellina$_{node-pert}$      0.824399  0.155283          0.465333  0.154295
Cellina-GAT$_{node-pert}$  0.845560  0.152392          0.507857  0.144932
SpatialProp$_{node-pert}$  0.691537  0.138045          0.070667  0.067731

                          edistance_pca_log             rmse_lfc
                                       mean       std       mean       std
model_name
mean shift                        25.155129  4.685970  10.980941  2.780590
CPA                                6.549658  2.018487   6.361472  4.713819
scGen                              5.651326  4.733550   6.479954  3.971814
MintFlow                          19.579815  1.728324   7.238124  5.409321
CONCERT                           24.941305  2.098372   7.452570  4.994117
Cellina (ablated)                  8.953372  5.239907   6.864653  4.480138
Cellina                            7.908895  1.287460   6.189643  4.839527
Cellina-GAT                        8.698390  1.491608   5.801605  4.498409
Cellina$_{node-pert}$              9.070849  1.859395   6.312573  4.764282
Cellina-GAT$_{node-pert}$          8.604325  1.430712   5.860258  4.426660
SpatialProp$_{node-pert}$         22.401546  3.155296   6.936263  2.557048

In [31]:
def find_best(agg: pd.DataFrame) -> dict:
    best = {}
    if isinstance(agg.index, pd.MultiIndex):
        # agg index: (perturbation, model_name)
        # collect perturbations preserving order
        raw = [p for p, _ in agg.index.tolist()]
        seen = set()
        perturbations = [p for p in raw if not (p in seen or seen.add(p))]
        for metric, direction in METRICS.items():
            for pert in perturbations:
                try:
                    means = agg.loc[pert][(metric, "mean")].dropna()
                except KeyError:
                    continue
                if means.empty:
                    continue
                best[(pert, metric)] = means.idxmax() if direction > 0 else means.idxmin()
    else:
        for metric, direction in METRICS.items():
            means = agg[(metric, "mean")].dropna()
            if means.empty:
                continue
            best[metric] = means.idxmax() if direction > 0 else means.idxmin()
    return best


def format_cell(mean, std, bold, na_str="--"):
    if pd.isna(mean):
        return na_str
    s = f"{mean:.2f} $\\pm$ {std:.2f}" if not pd.isna(std) else f"{mean:.2f}"
    return f"\\textbf{{{s}}}" if bold else s

In [32]:
best = find_best(df_avg)
table = pd.DataFrame(index=df_avg.index, columns=[PRETTY_METRIC[m] for m in METRICS])

for metric in METRICS:
    col = PRETTY_METRIC[metric]
    for model in df_avg.index:
        model_name = model

        mean = df_avg.loc[model, (metric, "mean")]
        std = df_avg.loc[model, (metric, "std")]

        bold = (best.get(metric) == model_name)

        table.loc[model, col] = format_cell(mean, std, bold)
table

,Pearson $\uparrow$,Signed Precision $\uparrow$,E-distance $\downarrow$,RMSE\textsubscript{LFC} $\downarrow$
model_name,,,,
mean shift,0.43 $\pm$ 0.23,0.12 $\pm$ 0.09,25.16 $\pm$ 4.69,10.98 $\pm$ 2.78
CPA,0.82 $\pm$ 0.16,0.44 $\pm$ 0.13,6.55 $\pm$ 2.02,6.36 $\pm$ 4.71
scGen,0.77 $\pm$ 0.16,0.20 $\pm$ 0.14,\textbf{5.65 $\pm$ 4.73},6.48 $\pm$ 3.97
MintFlow,0.81 $\pm$ 0.17,0.29 $\pm$ 0.16,19.58 $\pm$ 1.73,7.24 $\pm$ 5.41
CONCERT,0.77 $\pm$ 0.16,0.18 $\pm$ 0.15,24.94 $\pm$ 2.10,7.45 $\pm$ 4.99
Cellina (ablated),0.79 $\pm$ 0.15,0.37 $\pm$ 0.17,8.95 $\pm$ 5.24,6.86 $\pm$ 4.48
Cellina,0.83 $\pm$ 0.16,0.48 $\pm$ 0.16,7.91 $\pm$ 1.29,6.19 $\pm$ 4.84
Cellina-GAT,\textbf{0.85 $\pm$ 0.15},\textbf{0.52 $\pm$ 0.14},8.70 $\pm$ 1.49,\textbf{5.80 $\pm$ 4.50}
Cellina$_{node-pert}$,0.82 $\pm$ 0.16,0.47 $\pm$ 0.15,9.07 $\pm$ 1.86,6.31 $\pm$ 4.76
Cellina-GAT$_{node-pert}$,0.85 $\pm$ 0.15,0.51 $\pm$ 0.14,8.60 $\pm$ 1.43,5.86 $\pm$ 4.43
SpatialProp$_{node-pert}$,0.69 $\pm$ 0.14,0.07 $\pm$ 0.07,22.40 $\pm$ 3.16,6.94 $\pm$ 2.56

In [ ]:
flat = table.reset_index(level=0, drop=False)

latex = flat.to_latex(
    index=False,
    index_names=True,
    escape=False,
    column_format="l" + "c" * flat.shape[1],
    caption=(
        f"Leave-one-celltype-out performance (top {N_DEG} DEGs). "
        "Mean $\\pm$ std across slides. Best per metric in \\textbf{bold}."
    ),
    label=f"tab:loo_summary_{DATASET_NAME}",
)
latex = latex.replace("\\begin{table}", "\\begin{table}[t]\n\\centering")

print(latex)

(OUT_DIR / f"loo_summary_{DATASET_NAME}_DEG_{N_DEG}_table_avg.tex").write_text(latex)