# LOO summary table (DEG 200)

Builds a NeurIPS-ready summary table from `results/loo_summary_deg_200.csv`.

- Aggregates across seeds and held-out cell types (mean ± std).
- Bolds the best performer per metric (direction-aware).
- Renames `baseline` to `mean shift`.
- Annotates columns with ↑ (higher is better) or ↓ (lower is better).

In [20]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [21]:
import pandas as pd
from pathlib import Path

In [22]:
DATASET_NAME = "crc"
N_DEG = 50
CSV_PATH = f"../results/loo_summary_{DATASET_NAME}_DEG_{N_DEG}_camready.csv"
OUT_DIR = Path("../results")
OUT_DIR.mkdir(exist_ok=True)

df = pd.read_csv(CSV_PATH, engine="python")
df.head()

,sid,model_name,holdout_celltype,n_deg,spearman,pearson,precision,direction_match,direction_match_k,direction_match_gt,mixing_index,edistance_global,edistance_local,edistance_pca,edistance_pca_log,rmse,mse_lfc,nb_deviance
0,crc_120,baseline,Endothelial_CRC,50,0.571861,0.551004,0.10,1.0,0.10,0.98,0.540591,81.282657,82.961148,362.748829,22.239514,5851.174053,12.837272,0.650423
1,crc_120,baseline,Epithelial_CRC,50,0.432701,0.317540,0.20,0.8,0.16,0.64,0.896087,65.582195,66.306894,981.371974,51.017481,650873.943596,33.151102,0.725114
2,crc_120,baseline,Fibroblast_CRC,50,0.362689,0.391688,0.16,1.0,0.16,0.64,0.605597,83.394724,83.967733,929.818700,24.598781,179619.295161,11.690496,0.499658
3,crc_120,baseline,Myeloid_CRC,50,0.493205,0.481838,0.14,1.0,0.14,0.72,0.504394,81.406962,81.114779,386.495580,22.830676,36229.938262,11.068008,0.579255
4,crc_120,baseline,T_cell_CRC,50,0.826939,0.713368,0.12,1.0,0.12,0.96,0.784828,88.390381,93.439973,226.533829,22.346776,22622.722118,18.987500,0.543489

In [23]:
# Rename holdout_celltype by replacing the last '_' in with '-'
if DATASET_NAME == "merfish":
    df["holdout_celltype"] = df["holdout_celltype"].str.replace("Fiber_tracts", "Fiber-tracts", regex=False)
else:
    df["holdout_celltype"] = df["holdout_celltype"].str.replace("T_cell", "T-cell", regex=False)

In [24]:
# Split holdout_celltype on '_' and place everything in [0] as holdout_celltype, and everything in [1:] as perturbation
df["perturbation"] = df["holdout_celltype"].apply(lambda x: "".join(x.split("_")[-1]) if len(x.split("_")) > 1 else "")
df["holdout_celltype"] = df["holdout_celltype"].apply(lambda x: "-".join(x.split("_")[:-1]))
df

,sid,model_name,holdout_celltype,n_deg,spearman,pearson,precision,direction_match,direction_match_k,direction_match_gt,mixing_index,edistance_global,edistance_local,edistance_pca,edistance_pca_log,rmse,mse_lfc,nb_deviance,perturbation
0,crc_120,baseline,Endothelial,50,0.571861,0.551004,0.10,1.000000,0.10,0.98,0.540591,81.282657,82.961148,362.748829,22.239514,5851.174053,12.837272,0.650423,CRC
1,crc_120,baseline,Epithelial,50,0.432701,0.317540,0.20,0.800000,0.16,0.64,0.896087,65.582195,66.306894,981.371974,51.017481,650873.943596,33.151102,0.725114,CRC
2,crc_120,baseline,Fibroblast,50,0.362689,0.391688,0.16,1.000000,0.16,0.64,0.605597,83.394724,83.967733,929.818700,24.598781,179619.295161,11.690496,0.499658,CRC
3,crc_120,baseline,Myeloid,50,0.493205,0.481838,0.14,1.000000,0.14,0.72,0.504394,81.406962,81.114779,386.495580,22.830676,36229.938262,11.068008,0.579255,CRC
4,crc_120,baseline,T-cell,50,0.826939,0.713368,0.12,1.000000,0.12,0.96,0.784828,88.390381,93.439973,226.533829,22.346776,22622.722118,18.987500,0.543489,CRC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,crc_242,terra-lora-final,Endothelial,50,0.439712,0.711302,0.08,1.000000,0.08,0.86,0.374073,59.148634,57.937322,268.013755,4.986240,3259.760622,3.837546,0.577808,CRC
386,crc_242,terra-lora-final,Epithelial,50,0.047779,0.055695,0.12,0.666667,0.08,0.56,0.285285,55.180624,56.231225,560.489917,10.592197,83160.415095,14.760070,0.606220,CRC
387,crc_242,terra-lora-final,Fibroblast,50,0.388812,0.298447,0.20,0.700000,0.14,0.68,0.580168,60.375821,55.116639,506.219496,4.774208,33810.586465,4.138949,0.506336,CRC
388,crc_242,terra-lora-final,Myeloid,50,0.272125,0.459267,0.12,0.833333,0.10,0.84,0.956432,50.780039,49.024539,326.580119,5.436220,5240.238807,3.358800,0.491785,CRC
389,crc_242,terra-lora-final,T-cell,50,0.298727,0.361925,0.10,0.800000,0.08,0.70,0.626510,73.442423,76.031246,173.555825,3.510660,18465.471734,1.942587,0.520640,CRC

In [25]:
# Apply log10 on rmse
import numpy as np
df['rmse'] = np.log10(df['rmse'])

In [26]:
# Apply square root to mse_lfc
df['rmse_lfc'] = np.sqrt(df['mse_lfc'])

In [27]:
# Metrics we want in the table and whether higher (+1) or lower (-1) is better.
METRICS = {
    #"spearman": +1,
    "pearson": +1,
    "direction_match_k": +1,
    #"edistance_global": -1,
    "edistance_pca_log": -1,
    #"rmse": -1,
    "rmse_lfc": -1,
    #"avg_rank": -1,
    "nb_deviance": -1,
}

PRETTY_METRIC = {
    #"spearman": r"Spearman $\uparrow$",
    "pearson": r"Pearson $\uparrow$",
    "direction_match_k": r"Signed Precision $\uparrow$",
    #"edistance_global": r"E-dist (global) $\downarrow$",
    "edistance_pca_log": r"E-distance $\downarrow$",
    #"rmse": r"RMSE\textsubscript{counts} $\downarrow$",
    "rmse_lfc": r"RMSE\textsubscript{LFC} $\downarrow$",
    #"avg_rank": r"Avg. Rank $\downarrow$",
    "nb_deviance": r"NB Deviance $\downarrow$",
}

# Model display order + renaming (baseline -> mean shift).
MODEL_RENAME = {
    "baseline": "mean shift",
    "cpa": "CPA",
    "scgen": "scGen",
    "mintflow": "MintFlow",
    "concert": "CONCERT",
    "cellina-ablated": "Cellina (ablated)",
    "cellina-gat": "Cellina-GAT",
    "cellina": "Cellina",
    "cellina-pert": r"Cellina$_{node-pert}$",
    "cellina-gat-pert": r"Cellina-GAT$_{node-pert}$",
    "spatialprop-pert": r"SpatialProp$_{node-pert}$"
}
MODEL_ORDER = [
    "mean shift",
    "CPA",
    "scGen",
    "MintFlow",
    "CONCERT",
    "Cellina (ablated)",
    "Cellina",
    "Cellina-GAT",
    r"Cellina$_{node-pert}$",
    r"Cellina-GAT$_{node-pert}$",
    r"SpatialProp$_{node-pert}$",
]

df["model_name"] = df["model_name"].map(lambda x: MODEL_RENAME.get(x, x))
df["model_name"].unique()

array(['mean shift', 'Cellina (ablated)', 'Cellina$_{node-pert}$',
       'Cellina', 'Cellina-GAT$_{node-pert}$', 'Cellina-GAT', 'CONCERT',
       'CPA', 'scGen', 'MintFlow', 'SpatialProp$_{node-pert}$',
       'terra-frozen', 'terra-lora-final'], dtype=object)

In [28]:
# Two-step aggregation:
#   1) within each slide, average over held-out cell types
#   2) across slides, compute mean ± std
agg = (
    df.groupby(["perturbation", "model_name"])[list(METRICS)]
    .agg(["mean", "std"])
)

# Ensure a consistent model order within each perturbation. Build a
# MultiIndex with (perturbation, model) in the desired display order and
# reindex the aggregated table to that index.
perturbations = list(df["perturbation"].dropna().unique())
# keep stable ordering; treat empty string as its own group if present
if any(p == "" for p in perturbations):
    perturbations = sorted(perturbations, key=lambda x: (x != "", x))
else:
    perturbations = sorted(perturbations)

desired_index = pd.MultiIndex.from_product(
    [perturbations, MODEL_ORDER], names=["perturbation", "model_name"]
)
agg = agg.reindex(desired_index)
agg

                                         pearson           direction_match_k  \
                                            mean       std              mean
perturbation model_name
CRC          mean shift                 0.514166  0.256655          0.184667
             CPA                        0.680111  0.191169          0.221333
             scGen                      0.504303  0.366677          0.192667
             MintFlow                   0.653811  0.314868          0.228000
             CONCERT                    0.494732  0.428738          0.210667
             Cellina (ablated)          0.713606  0.244170          0.308000
             Cellina                    0.862574  0.173476          0.453333
             Cellina-GAT                0.889207  0.092331          0.418667
             Cellina$_{node-pert}$      0.804640  0.175411          0.358000
             Cellina-GAT$_{node-pert}$  0.876068  0.091586          0.396000
             SpatialProp$_{node-pert}$  0.460661  0.287072          0.063333

                                                 edistance_pca_log             \
                                             std              mean        std
perturbation model_name
CRC          mean shift                 0.145809         29.844808  10.466223
             CPA                        0.188857          6.437130   2.281013
             scGen                      0.196906          4.565423   3.461835
             MintFlow                   0.209077         13.047200   1.798953
             CONCERT                    0.216666         29.975491   5.211521
             Cellina (ablated)          0.216212          4.930526   1.658010
             Cellina                    0.185720          6.997138   1.054692
             Cellina-GAT                0.197077          8.590365   1.895135
             Cellina$_{node-pert}$      0.191355          7.198875   1.453078
             Cellina-GAT$_{node-pert}$  0.175255         11.345882   3.255842
             SpatialProp$_{node-pert}$  0.113512         27.117155   8.506848

                                        rmse_lfc           nb_deviance  \
                                            mean       std        mean
perturbation model_name
CRC          mean shift                 5.080482  2.506828    0.435466
             CPA                        1.501718  0.558820    0.041692
             scGen                      1.994265  0.837424    0.087035
             MintFlow                   1.513357  0.426727    0.503996
             CONCERT                    1.810221  0.674649    0.053165
             Cellina (ablated)          1.510071  0.880103    0.035556
             Cellina                    1.139673  0.560219    0.027145
             Cellina-GAT                1.092881  0.614187    0.028735
             Cellina$_{node-pert}$      1.389687  0.755065    0.032239
             Cellina-GAT$_{node-pert}$  1.082055  0.490295    0.033220
             SpatialProp$_{node-pert}$  7.391718  1.232582    6.596930


                                             std
perturbation model_name
CRC          mean shift                 0.133711
             CPA                        0.047070
             scGen                      0.034919
             MintFlow                   0.140064
             CONCERT                    0.043030
             Cellina (ablated)          0.043166
             Cellina                    0.032222
             Cellina-GAT                0.035995
             Cellina$_{node-pert}$      0.038532
             Cellina-GAT$_{node-pert}$  0.048699
             SpatialProp$_{node-pert}$  4.218942

In [29]:
def find_best(agg: pd.DataFrame) -> dict:
    best = {}
    if isinstance(agg.index, pd.MultiIndex):
        # agg index: (perturbation, model_name)
        # collect perturbations preserving order
        raw = [p for p, _ in agg.index.tolist()]
        seen = set()
        perturbations = [p for p in raw if not (p in seen or seen.add(p))]
        for metric, direction in METRICS.items():
            for pert in perturbations:
                try:
                    means = agg.loc[pert][(metric, "mean")].dropna()
                except KeyError:
                    continue
                if means.empty:
                    continue
                best[(pert, metric)] = means.idxmax() if direction > 0 else means.idxmin()
    else:
        for metric, direction in METRICS.items():
            means = agg[(metric, "mean")].dropna()
            if means.empty:
                continue
            best[metric] = means.idxmax() if direction > 0 else means.idxmin()
    return best


def format_cell(mean, std, bold, na_str="--"):
    if pd.isna(mean):
        return na_str
    s = f"{mean:.2f} $\\pm$ {std:.2f}" if not pd.isna(std) else f"{mean:.2f}"
    return f"\\textbf{{{s}}}" if bold else s

In [30]:
best = find_best(agg)
table = pd.DataFrame(index=agg.index, columns=[PRETTY_METRIC[m] for m in METRICS])

for metric in METRICS:
    col = PRETTY_METRIC[metric]
    for model in agg.index:
        pert, model_name = model

        mean = agg.loc[model, (metric, "mean")]
        std = agg.loc[model, (metric, "std")]

        bold = (best.get((pert, metric)) == model_name)

        table.loc[model, col] = format_cell(mean, std, bold)
table

                                              Pearson $\uparrow$  \
perturbation model_name
CRC          mean shift                          0.51 $\pm$ 0.26
             CPA                                 0.68 $\pm$ 0.19
             scGen                               0.50 $\pm$ 0.37
             MintFlow                            0.65 $\pm$ 0.31
             CONCERT                             0.49 $\pm$ 0.43
             Cellina (ablated)                   0.71 $\pm$ 0.24
             Cellina                             0.86 $\pm$ 0.17
             Cellina-GAT                \textbf{0.89 $\pm$ 0.09}
             Cellina$_{node-pert}$               0.80 $\pm$ 0.18
             Cellina-GAT$_{node-pert}$           0.88 $\pm$ 0.09
             SpatialProp$_{node-pert}$           0.46 $\pm$ 0.29

                                       Signed Precision $\uparrow$  \
perturbation model_name
CRC          mean shift                            0.18 $\pm$ 0.15
             CPA                                   0.22 $\pm$ 0.19
             scGen                                 0.19 $\pm$ 0.20
             MintFlow                              0.23 $\pm$ 0.21
             CONCERT                               0.21 $\pm$ 0.22
             Cellina (ablated)                     0.31 $\pm$ 0.22
             Cellina                      \textbf{0.45 $\pm$ 0.19}
             Cellina-GAT                           0.42 $\pm$ 0.20
             Cellina$_{node-pert}$                 0.36 $\pm$ 0.19
             Cellina-GAT$_{node-pert}$             0.40 $\pm$ 0.18
             SpatialProp$_{node-pert}$             0.06 $\pm$ 0.11

                                         E-distance $\downarrow$  \
perturbation model_name
CRC          mean shift                        29.84 $\pm$ 10.47
             CPA                                 6.44 $\pm$ 2.28
             scGen                      \textbf{4.57 $\pm$ 3.46}
             MintFlow                           13.05 $\pm$ 1.80
             CONCERT                            29.98 $\pm$ 5.21
             Cellina (ablated)                   4.93 $\pm$ 1.66
             Cellina                             7.00 $\pm$ 1.05
             Cellina-GAT                         8.59 $\pm$ 1.90
             Cellina$_{node-pert}$               7.20 $\pm$ 1.45
             Cellina-GAT$_{node-pert}$          11.35 $\pm$ 3.26
             SpatialProp$_{node-pert}$          27.12 $\pm$ 8.51

                                       RMSE\textsubscript{LFC} $\downarrow$  \
perturbation model_name
CRC          mean shift                                     5.08 $\pm$ 2.51
             CPA                                            1.50 $\pm$ 0.56
             scGen                                          1.99 $\pm$ 0.84
             MintFlow                                       1.51 $\pm$ 0.43
             CONCERT                                        1.81 $\pm$ 0.67
             Cellina (ablated)                              1.51 $\pm$ 0.88
             Cellina                                        1.14 $\pm$ 0.56
             Cellina-GAT                                    1.09 $\pm$ 0.61
             Cellina$_{node-pert}$                          1.39 $\pm$ 0.76
             Cellina-GAT$_{node-pert}$             \textbf{1.08 $\pm$ 0.49}
             SpatialProp$_{node-pert}$                      7.39 $\pm$ 1.23

                                        NB Deviance $\downarrow$
perturbation model_name
CRC          mean shift                          0.44 $\pm$ 0.13
             CPA                                 0.04 $\pm$ 0.05
             scGen                               0.09 $\pm$ 0.03
             MintFlow                            0.50 $\pm$ 0.14
             CONCERT                             0.05 $\pm$ 0.04
             Cellina (ablated)                   0.04 $\pm$ 0.04
             Cellina                    \textbf{0.03 $\pm$ 0.03}
             Cellina-GAT                         0.03 $\pm$ 0.04
             Cellina$_{node-pert}$               0.03 $\pm$ 0.04
             Cellina-GAT$_{node-pert}$           0.03 $\pm$ 0.05
             SpatialProp$_{node-pert}$           6.60 $\pm$ 4.22

In [31]:
def insert_midrule_perts(latex, table):
    groups = table.index.get_level_values(0)
    boundaries = [i for i in range(1, len(groups)) if groups[i] != groups[i - 1]]

    lines = latex.splitlines()
    new_lines = []

    row_idx = 0

    for line in lines:
        new_lines.append(line)

        # detect data rows (skip header)
        if "&" in line and "\\\\" in line:
            if row_idx in boundaries:
                new_lines.append(r"\midrule")
            row_idx += 1

    latex = "\n".join(new_lines)
    return latex

In [32]:
is_multi_pert = table.index.get_level_values(0).nunique() > 1

if is_multi_pert:
    latex = table.to_latex(
        index_names=False, # removes the extra header row
        escape=False,
        header=False,
        column_format="ll" + "c" * table.shape[1],  # two index levels → 'll'
        multirow=True,  # for multiple perturbations
        caption=(
            f"Leave-one-celltype-out performance (top {N_DEG} DEGs). For each slide we "
            "first average over the held-out cell types, then report mean $\\pm$ std "
            f"across {df['sid'].nunique()} slides. Best per metric in \\textbf{{bold}}."
        ),
        label=f"tab:loo_summary_{DATASET_NAME}",
    )

    latex = latex.replace(r"\cline{1-7}", "")
    latex = latex.replace("\\begin{table}", "\\begin{table}[t]\n\\centering")
    latex = latex.replace(r"\multirow[t]", r"\multirow[c]")
    header = "Holdout \\\ perturbation & Method & " + " & ".join(table.columns) + r" \\"
    latex = latex.replace(
    "\\begin{tabular}{ll" + "c" * table.shape[1] + "}",
    "\\begin{tabular}{ll" + "c" * table.shape[1] + "}\n\\toprule\n" + header
    )
    latex = latex.replace(r"\midrule", "")
    latex = insert_midrule_perts(latex, table)
else:
    flat = table.reset_index(level=0, drop=True)

    latex = flat.to_latex(
        index=True,
        index_names=False,
        escape=False,
        column_format="l" + "c" * flat.shape[1],
        caption=(
            f"Leave-one-celltype-out performance (top {N_DEG} DEGs). "
            "Mean $\\pm$ std across slides. Best per metric in \\textbf{bold}."
        ),
        label=f"tab:loo_summary_{DATASET_NAME}",
    )
    latex = latex.replace("\\begin{table}", "\\begin{table}[t]\n\\centering")

print(latex)

(OUT_DIR / f"loo_summary_{DATASET_NAME}_DEG_{N_DEG}_table.tex").write_text(latex)

\begin{table}[t]
\centering
\caption{Leave-one-celltype-out performance (top 50 DEGs). Mean $\pm$ std across slides. Best per metric in \textbf{bold}.}
\label{tab:loo_summary_crc}
\begin{tabular}{lccccc}
\toprule
 & Pearson $\uparrow$ & Signed Precision $\uparrow$ & E-distance $\downarrow$ & RMSE\textsubscript{LFC} $\downarrow$ & NB Deviance $\downarrow$ \\
\midrule
mean shift & 0.51 $\pm$ 0.26 & 0.18 $\pm$ 0.15 & 29.84 $\pm$ 10.47 & 5.08 $\pm$ 2.51 & 0.44 $\pm$ 0.13 \\
CPA & 0.68 $\pm$ 0.19 & 0.22 $\pm$ 0.19 & 6.44 $\pm$ 2.28 & 1.50 $\pm$ 0.56 & 0.04 $\pm$ 0.05 \\
scGen & 0.50 $\pm$ 0.37 & 0.19 $\pm$ 0.20 & \textbf{4.57 $\pm$ 3.46} & 1.99 $\pm$ 0.84 & 0.09 $\pm$ 0.03 \\
MintFlow & 0.65 $\pm$ 0.31 & 0.23 $\pm$ 0.21 & 13.05 $\pm$ 1.80 & 1.51 $\pm$ 0.43 & 0.50 $\pm$ 0.14 \\
CONCERT & 0.49 $\pm$ 0.43 & 0.21 $\pm$ 0.22 & 29.98 $\pm$ 5.21 & 1.81 $\pm$ 0.67 & 0.05 $\pm$ 0.04 \\
Cellina (ablated) & 0.71 $\pm$ 0.24 & 0.31 $\pm$ 0.22 & 4.93 $\pm$ 1.66 & 1.51 $\pm$ 0.88 & 0.04 $\pm$ 0.04 \\
Cellina & 0.86 $\pm$ 0.17 & \textbf{0.45 $\pm$ 0.19} & 7.00 $\pm$ 1.05 & 1.14 $\pm$ 0.56 & \textbf{0.03 $\pm$ 0.03} \\
Cellina-GAT & \textbf{0.89 $\pm$ 0.09} & 0.42 $\pm$ 0.20 & 8.59 $\pm$ 1.90 & 1.09 $\pm$ 0.61 & 0.03 $\pm$ 0.04 \\
Cellina$_{node-pert}$ & 0.80 $\pm$ 0.18 & 0.36 $\pm$ 0.19 & 7.20 $\pm$ 1.45 & 1.39 $\pm$ 0.76 & 0.03 $\pm$ 0.04 \\
Cellina-GAT$_{node-pert}$ & 0.88 $\pm$ 0.09 & 0.40 $\pm$ 0.18 & 11.35 $\pm$ 3.26 & \textbf{1.08 $\pm$ 0.49} & 0.03 $\pm$ 0.05 \\
SpatialProp$_{node-pert}$ & 0.46 $\pm$ 0.29 & 0.06 $\pm$ 0.11 & 27.12 $\pm$ 8.51 & 7.39 $\pm$ 1.23 & 6.60 $\pm$ 4.22 \\
\bottomrule
\end{tabular}
\end{table}

1631

***

In [33]:
agg

                                         pearson           direction_match_k  \
                                            mean       std              mean
perturbation model_name
CRC          mean shift                 0.514166  0.256655          0.184667
             CPA                        0.680111  0.191169          0.221333
             scGen                      0.504303  0.366677          0.192667
             MintFlow                   0.653811  0.314868          0.228000
             CONCERT                    0.494732  0.428738          0.210667
             Cellina (ablated)          0.713606  0.244170          0.308000
             Cellina                    0.862574  0.173476          0.453333
             Cellina-GAT                0.889207  0.092331          0.418667
             Cellina$_{node-pert}$      0.804640  0.175411          0.358000
             Cellina-GAT$_{node-pert}$  0.876068  0.091586          0.396000
             SpatialProp$_{node-pert}$  0.460661  0.287072          0.063333

                                                 edistance_pca_log             \
                                             std              mean        std
perturbation model_name
CRC          mean shift                 0.145809         29.844808  10.466223
             CPA                        0.188857          6.437130   2.281013
             scGen                      0.196906          4.565423   3.461835
             MintFlow                   0.209077         13.047200   1.798953
             CONCERT                    0.216666         29.975491   5.211521
             Cellina (ablated)          0.216212          4.930526   1.658010
             Cellina                    0.185720          6.997138   1.054692
             Cellina-GAT                0.197077          8.590365   1.895135
             Cellina$_{node-pert}$      0.191355          7.198875   1.453078
             Cellina-GAT$_{node-pert}$  0.175255         11.345882   3.255842
             SpatialProp$_{node-pert}$  0.113512         27.117155   8.506848

                                        rmse_lfc           nb_deviance  \
                                            mean       std        mean
perturbation model_name
CRC          mean shift                 5.080482  2.506828    0.435466
             CPA                        1.501718  0.558820    0.041692
             scGen                      1.994265  0.837424    0.087035
             MintFlow                   1.513357  0.426727    0.503996
             CONCERT                    1.810221  0.674649    0.053165
             Cellina (ablated)          1.510071  0.880103    0.035556
             Cellina                    1.139673  0.560219    0.027145
             Cellina-GAT                1.092881  0.614187    0.028735
             Cellina$_{node-pert}$      1.389687  0.755065    0.032239
             Cellina-GAT$_{node-pert}$  1.082055  0.490295    0.033220
             SpatialProp$_{node-pert}$  7.391718  1.232582    6.596930


                                             std
perturbation model_name
CRC          mean shift                 0.133711
             CPA                        0.047070
             scGen                      0.034919
             MintFlow                   0.140064
             CONCERT                    0.043030
             Cellina (ablated)          0.043166
             Cellina                    0.032222
             Cellina-GAT                0.035995
             Cellina$_{node-pert}$      0.038532
             Cellina-GAT$_{node-pert}$  0.048699
             SpatialProp$_{node-pert}$  4.218942

In [34]:
df_avg = agg.groupby(level="model_name").mean()

In [35]:
df_avg = df_avg.loc[MODEL_ORDER]
df_avg

                            pearson           direction_match_k            \
                               mean       std              mean       std
model_name
mean shift                 0.514166  0.256655          0.184667  0.145809
CPA                        0.680111  0.191169          0.221333  0.188857
scGen                      0.504303  0.366677          0.192667  0.196906
MintFlow                   0.653811  0.314868          0.228000  0.209077
CONCERT                    0.494732  0.428738          0.210667  0.216666
Cellina (ablated)          0.713606  0.244170          0.308000  0.216212
Cellina                    0.862574  0.173476          0.453333  0.185720
Cellina-GAT                0.889207  0.092331          0.418667  0.197077
Cellina$_{node-pert}$      0.804640  0.175411          0.358000  0.191355
Cellina-GAT$_{node-pert}$  0.876068  0.091586          0.396000  0.175255
SpatialProp$_{node-pert}$  0.460661  0.287072          0.063333  0.113512

                          edistance_pca_log             rmse_lfc            \
                                       mean        std      mean       std
model_name
mean shift                        29.844808  10.466223  5.080482  2.506828
CPA                                6.437130   2.281013  1.501718  0.558820
scGen                              4.565423   3.461835  1.994265  0.837424
MintFlow                          13.047200   1.798953  1.513357  0.426727
CONCERT                           29.975491   5.211521  1.810221  0.674649
Cellina (ablated)                  4.930526   1.658010  1.510071  0.880103
Cellina                            6.997138   1.054692  1.139673  0.560219
Cellina-GAT                        8.590365   1.895135  1.092881  0.614187
Cellina$_{node-pert}$              7.198875   1.453078  1.389687  0.755065
Cellina-GAT$_{node-pert}$         11.345882   3.255842  1.082055  0.490295
SpatialProp$_{node-pert}$         27.117155   8.506848  7.391718  1.232582

                          nb_deviance
                                 mean       std
model_name
mean shift                   0.435466  0.133711
CPA                          0.041692  0.047070
scGen                        0.087035  0.034919
MintFlow                     0.503996  0.140064
CONCERT                      0.053165  0.043030
Cellina (ablated)            0.035556  0.043166
Cellina                      0.027145  0.032222
Cellina-GAT                  0.028735  0.035995
Cellina$_{node-pert}$        0.032239  0.038532
Cellina-GAT$_{node-pert}$    0.033220  0.048699
SpatialProp$_{node-pert}$    6.596930  4.218942

In [36]:
def find_best(agg: pd.DataFrame) -> dict:
    best = {}
    if isinstance(agg.index, pd.MultiIndex):
        # agg index: (perturbation, model_name)
        # collect perturbations preserving order
        raw = [p for p, _ in agg.index.tolist()]
        seen = set()
        perturbations = [p for p in raw if not (p in seen or seen.add(p))]
        for metric, direction in METRICS.items():
            for pert in perturbations:
                try:
                    means = agg.loc[pert][(metric, "mean")].dropna()
                except KeyError:
                    continue
                if means.empty:
                    continue
                best[(pert, metric)] = means.idxmax() if direction > 0 else means.idxmin()
    else:
        for metric, direction in METRICS.items():
            means = agg[(metric, "mean")].dropna()
            if means.empty:
                continue
            best[metric] = means.idxmax() if direction > 0 else means.idxmin()
    return best


def format_cell(mean, std, bold, na_str="--"):
    if pd.isna(mean):
        return na_str
    s = f"{mean:.2f} $\\pm$ {std:.2f}" if not pd.isna(std) else f"{mean:.2f}"
    return f"\\textbf{{{s}}}" if bold else s

In [37]:
best = find_best(df_avg)
table = pd.DataFrame(index=df_avg.index, columns=[PRETTY_METRIC[m] for m in METRICS])

for metric in METRICS:
    col = PRETTY_METRIC[metric]
    for model in df_avg.index:
        model_name = model

        mean = df_avg.loc[model, (metric, "mean")]
        std = df_avg.loc[model, (metric, "std")]

        bold = (best.get(metric) == model_name)

        table.loc[model, col] = format_cell(mean, std, bold)
table

,Pearson $\uparrow$,Signed Precision $\uparrow$,E-distance $\downarrow$,RMSE\textsubscript{LFC} $\downarrow$,NB Deviance $\downarrow$
model_name,,,,,
mean shift,0.51 $\pm$ 0.26,0.18 $\pm$ 0.15,29.84 $\pm$ 10.47,5.08 $\pm$ 2.51,0.44 $\pm$ 0.13
CPA,0.68 $\pm$ 0.19,0.22 $\pm$ 0.19,6.44 $\pm$ 2.28,1.50 $\pm$ 0.56,0.04 $\pm$ 0.05
scGen,0.50 $\pm$ 0.37,0.19 $\pm$ 0.20,\textbf{4.57 $\pm$ 3.46},1.99 $\pm$ 0.84,0.09 $\pm$ 0.03
MintFlow,0.65 $\pm$ 0.31,0.23 $\pm$ 0.21,13.05 $\pm$ 1.80,1.51 $\pm$ 0.43,0.50 $\pm$ 0.14
CONCERT,0.49 $\pm$ 0.43,0.21 $\pm$ 0.22,29.98 $\pm$ 5.21,1.81 $\pm$ 0.67,0.05 $\pm$ 0.04
Cellina (ablated),0.71 $\pm$ 0.24,0.31 $\pm$ 0.22,4.93 $\pm$ 1.66,1.51 $\pm$ 0.88,0.04 $\pm$ 0.04
Cellina,0.86 $\pm$ 0.17,\textbf{0.45 $\pm$ 0.19},7.00 $\pm$ 1.05,1.14 $\pm$ 0.56,\textbf{0.03 $\pm$ 0.03}
Cellina-GAT,\textbf{0.89 $\pm$ 0.09},0.42 $\pm$ 0.20,8.59 $\pm$ 1.90,1.09 $\pm$ 0.61,0.03 $\pm$ 0.04
Cellina$_{node-pert}$,0.80 $\pm$ 0.18,0.36 $\pm$ 0.19,7.20 $\pm$ 1.45,1.39 $\pm$ 0.76,0.03 $\pm$ 0.04
Cellina-GAT$_{node-pert}$,0.88 $\pm$ 0.09,0.40 $\pm$ 0.18,11.35 $\pm$ 3.26,\textbf{1.08 $\pm$ 0.49},0.03 $\pm$ 0.05
SpatialProp$_{node-pert}$,0.46 $\pm$ 0.29,0.06 $\pm$ 0.11,27.12 $\pm$ 8.51,7.39 $\pm$ 1.23,6.60 $\pm$ 4.22

In [38]:
flat = table.reset_index(level=0, drop=False)

latex = flat.to_latex(
    index=False,
    index_names=True,
    escape=False,
    column_format="l" + "c" * flat.shape[1],
    caption=(
        f"Leave-one-celltype-out performance (top {N_DEG} DEGs). "
        "Mean $\\pm$ std across slides. Best per metric in \\textbf{bold}."
    ),
    label=f"tab:loo_summary_{DATASET_NAME}",
)
latex = latex.replace("\\begin{table}", "\\begin{table}[t]\n\\centering")

print(latex)

(OUT_DIR / f"loo_summary_{DATASET_NAME}_DEG_{N_DEG}_table_avg.tex").write_text(latex)

\begin{table}[t]
\centering
\caption{Leave-one-celltype-out performance (top 50 DEGs). Mean $\pm$ std across slides. Best per metric in \textbf{bold}.}
\label{tab:loo_summary_crc}
\begin{tabular}{lcccccc}
\toprule
model_name & Pearson $\uparrow$ & Signed Precision $\uparrow$ & E-distance $\downarrow$ & RMSE\textsubscript{LFC} $\downarrow$ & NB Deviance $\downarrow$ \\
\midrule
mean shift & 0.51 $\pm$ 0.26 & 0.18 $\pm$ 0.15 & 29.84 $\pm$ 10.47 & 5.08 $\pm$ 2.51 & 0.44 $\pm$ 0.13 \\
CPA & 0.68 $\pm$ 0.19 & 0.22 $\pm$ 0.19 & 6.44 $\pm$ 2.28 & 1.50 $\pm$ 0.56 & 0.04 $\pm$ 0.05 \\
scGen & 0.50 $\pm$ 0.37 & 0.19 $\pm$ 0.20 & \textbf{4.57 $\pm$ 3.46} & 1.99 $\pm$ 0.84 & 0.09 $\pm$ 0.03 \\
MintFlow & 0.65 $\pm$ 0.31 & 0.23 $\pm$ 0.21 & 13.05 $\pm$ 1.80 & 1.51 $\pm$ 0.43 & 0.50 $\pm$ 0.14 \\
CONCERT & 0.49 $\pm$ 0.43 & 0.21 $\pm$ 0.22 & 29.98 $\pm$ 5.21 & 1.81 $\pm$ 0.67 & 0.05 $\pm$ 0.04 \\
Cellina (ablated) & 0.71 $\pm$ 0.24 & 0.31 $\pm$ 0.22 & 4.93 $\pm$ 1.66 & 1.51 $\pm$ 0.88 & 0.04 $\pm$ 0.04 \\
Cellina & 0.86 $\pm$ 0.17 & \textbf{0.45 $\pm$ 0.19} & 7.00 $\pm$ 1.05 & 1.14 $\pm$ 0.56 & \textbf{0.03 $\pm$ 0.03} \\
Cellina-GAT & \textbf{0.89 $\pm$ 0.09} & 0.42 $\pm$ 0.20 & 8.59 $\pm$ 1.90 & 1.09 $\pm$ 0.61 & 0.03 $\pm$ 0.04 \\
Cellina$_{node-pert}$ & 0.80 $\pm$ 0.18 & 0.36 $\pm$ 0.19 & 7.20 $\pm$ 1.45 & 1.39 $\pm$ 0.76 & 0.03 $\pm$ 0.04 \\
Cellina-GAT$_{node-pert}$ & 0.88 $\pm$ 0.09 & 0.40 $\pm$ 0.18 & 11.35 $\pm$ 3.26 & \textbf{1.08 $\pm$ 0.49} & 0.03 $\pm$ 0.05 \\
SpatialProp$_{node-pert}$ & 0.46 $\pm$ 0.29 & 0.06 $\pm$ 0.11 & 27.12 $\pm$ 8.51 & 7.39 $\pm$ 1.23 & 6.60 $\pm$ 4.22 \\
\bottomrule
\end{tabular}
\end{table}

1642