In [37]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [38]:
import sys

sys.path.append('../scripts')

In [39]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
DATA_ROOT = '/data/a330d' #os.environ.get("DATA_ROOT", ".")
import numpy as np
import glob
import numpy as np
import json
import matplotlib as mpl
import re

from plotting import plot_model_comparison

In [40]:
dataset_name = "merfish" # Options: merfish, crc

In [41]:
corr_dir = os.path.join(DATA_ROOT, f"datasets/{dataset_name}/correlations")
pattern = os.path.join(corr_dir, "*.json")
files = sorted(glob.glob(pattern))

rows = []
for fp in files:
    name = os.path.basename(fp)
    core = name[len("crc_"):-len(".json")] if dataset_name == "crc" else name[:-len(".json")]
    parts = core.split("_")
    sid = parts[0]
    model_name = parts[1]
    # If model_name contains a number, then continue otherwise skip
    if not re.search(r'\d', model_name):
        continue
    holdout_celltype = "_".join(parts[2:])
    try:
        with open(fp, "r") as f:
            data = json.load(f)
    except Exception:
        # skip unreadable/invalid json
        continue

    try:
        rows.append({
            "sid": f"crc_{sid}" if dataset_name == "crc" else sid,
            "model_name": model_name,
            "holdout_celltype": holdout_celltype,
            "n_deg": data.get("n_deg"),
            "spearman": data.get("spearman"),
            "pearson": data.get("pearson"),
            "precision": data.get("precision"),
            "direction_match": data.get("direction_match"),
            "direction_match_k": data.get("direction_match_k"),
            "direction_match_gt": data.get("direction_match_gt"),
            "mixing_index": data.get("mixing_index"),
            "edistance_global": data.get("edistance_global"),
            "edistance_local": data.get("edistance_local"),
            "edistance_pca": data.get("edistance_pca"),
            "edistance_pca_log": data.get("edistance_pca_log"),           
            "rmse": data.get("rmse"),
            "mse_lfc": data.get("mse_lfc"),
            "nb_deviance": data.get("nb_deviance"),
        })
    except Exception as e:
        print(f"Error processing file {fp}: {e}")
        continue

df = pd.DataFrame(rows)
df.head()

,sid,model_name,holdout_celltype,n_deg,spearman,pearson,precision,direction_match,direction_match_k,direction_match_gt,mixing_index,edistance_global,edistance_local,edistance_pca,edistance_pca_log,rmse,mse_lfc,nb_deviance
0,C57BL6J-2.036,cellina-W-1-cf,GABAergic neuron_Fiber_tracts,50,0.870540,0.914610,0.62,1.000000,0.62,0.98,0.866848,40.097470,44.090670,690.544147,8.535579,842.119629,10.727286,NaN
1,C57BL6J-2.036,cellina-W-1-cf,GABAergic neuron_Isocortex,50,0.935078,0.972771,0.64,1.000000,0.64,1.00,0.701331,40.805359,44.339019,397.230850,9.382538,1319.698242,5.097899,NaN
2,C57BL6J-2.036,cellina-W-1-cf,astrocyte_Fiber_tracts,50,0.284226,0.470458,0.34,0.882353,0.30,0.70,0.576835,36.839698,36.999398,610.818726,7.696891,3955.918701,122.949661,NaN
3,C57BL6J-2.036,cellina-W-1-cf,astrocyte_Isocortex,50,0.884850,0.886652,0.50,1.000000,0.50,0.98,0.906251,39.668534,38.591734,371.862311,7.961316,3344.741455,10.312443,NaN
4,C57BL6J-2.036,cellina-W-1-cf,endothelial cell_Fiber_tracts,50,0.762209,0.994536,0.14,1.000000,0.14,0.78,0.933039,35.443476,35.453342,276.967090,6.514434,3950.766113,289.522278,NaN

In [42]:
n_deg = df["n_deg"].iloc[0]

In [43]:
df["sid"] = df["sid"].astype(str)
# Keep camera-ready version for cellina
keep_models = ["cellina-cr", "scgen", "cpa"]
df = df[df["model_name"].str.contains(
    "|".join(keep_models),
    na=False
)]
# Remove -cr from each cellina model name
df["model_name"] = df["model_name"].str.replace("-cr", "", regex=False)
# Remove -cf from the end of each model_name
df["model_name"] = df["model_name"].str.replace("-cf", "", regex=False)

In [44]:
df.model_name.unique()

array(['cellina-1', 'cellina-2', 'cpa-1', 'cpa-2', 'scgen-1', 'scgen-2'],
      dtype=object)

In [45]:
# Split model_name by '-' and add the last part as a new column 'seed'
df["seed"] = df["model_name"].str.split("-").str[-1]
df["model_name"] = df["model_name"].str.rsplit("-", n=1).str[0]

In [46]:
df

,sid,model_name,holdout_celltype,n_deg,spearman,pearson,precision,direction_match,direction_match_k,direction_match_gt,mixing_index,edistance_global,edistance_local,edistance_pca,edistance_pca_log,rmse,mse_lfc,nb_deviance,seed
20,C57BL6J-2.036,cellina,GABAergic neuron_Fiber_tracts,50,0.903001,0.916574,0.68,1.000000,0.68,0.98,0.866848,36.511606,42.586272,605.825317,7.898999,855.535950,10.265101,0.029604,1
21,C57BL6J-2.036,cellina,GABAergic neuron_Isocortex,50,0.936903,0.974602,0.66,1.000000,0.66,1.00,0.694179,41.242681,46.412652,378.087714,9.572641,1325.852661,4.839458,0.070864,1
22,C57BL6J-2.036,cellina,astrocyte_Fiber_tracts,50,0.344730,0.494441,0.38,0.894737,0.34,0.74,0.623076,32.876234,34.669748,420.287482,5.953089,3692.632324,119.274025,0.022515,1
23,C57BL6J-2.036,cellina,astrocyte_Isocortex,50,0.893878,0.891688,0.58,1.000000,0.58,0.96,0.550894,37.883680,37.036945,318.547528,6.952761,3228.286133,9.688178,0.016515,1
24,C57BL6J-2.036,cellina,endothelial cell_Fiber_tracts,50,0.719856,0.992141,0.14,1.000000,0.14,0.82,0.972162,33.310241,34.033472,246.914185,6.105460,3902.595947,286.794281,0.007785,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,C57BL6J-2.041,scgen,endothelial cell_Isocortex,50,0.859592,0.935010,0.64,1.000000,0.64,0.98,0.374996,6.500793,7.986438,1175.970825,1.823242,2023.291992,39.296463,NaN,2
236,C57BL6J-2.041,scgen,glutamatergic neuron_Fiber_tracts,50,0.409172,0.419003,0.02,1.000000,0.02,0.52,0.964858,12.918408,22.815159,798.195447,10.640639,9040.429688,15.868780,NaN,2
237,C57BL6J-2.041,scgen,glutamatergic neuron_Isocortex,50,0.669436,0.913734,0.16,1.000000,0.16,1.00,0.696909,13.044511,23.099547,846.152399,11.785520,12593.227539,18.105450,NaN,2
238,C57BL6J-2.041,scgen,oligodendrocyte_Fiber_tracts,50,0.180696,0.753265,0.16,1.000000,0.16,0.94,0.372380,3.913896,5.378552,1352.077759,1.508288,3780.251221,12.099734,NaN,2
239,C57BL6J-2.041,scgen,oligodendrocyte_Isocortex,50,0.295462,0.537224,0.04,1.000000,0.04,0.92,0.593448,5.348476,7.466949,707.847156,2.169936,4682.176758,194.829544,NaN,2

In [47]:
old = pd.read_csv(f"../results/loo_summary_{dataset_name}_DEG_{n_deg}_camready.csv")

# Only keep model_name which exists in df
old = old[old["model_name"].isin(df["model_name"])]
old['seed'] = 0

In [48]:
# concat df and old
combined_df = pd.concat([df, old], ignore_index=True)

In [49]:
combined_df.model_name.unique()

array(['cellina', 'cpa', 'scgen'], dtype=object)

In [50]:
combined_df = combined_df.rename(columns={"direction_match_k": "signed_precision"})
combined_df = combined_df.rename(columns={"edistance_pca_log": "e-distance"})

In [51]:
combined_df['rmse'] = np.log10(combined_df['rmse'])
combined_df['rmse_lfc'] = np.sqrt(combined_df['mse_lfc'])

In [52]:
combined_df

,sid,model_name,holdout_celltype,n_deg,spearman,pearson,precision,direction_match,signed_precision,direction_match_gt,mixing_index,edistance_global,edistance_local,edistance_pca,e-distance,rmse,mse_lfc,nb_deviance,seed,rmse_lfc
0,C57BL6J-2.036,cellina,GABAergic neuron_Fiber_tracts,50,0.903001,0.916574,0.68,1.000000,0.68,0.98,0.866848,36.511606,42.586272,605.825317,7.898999,2.932238,10.265101,0.029604,1,3.203920
1,C57BL6J-2.036,cellina,GABAergic neuron_Isocortex,50,0.936903,0.974602,0.66,1.000000,0.66,1.00,0.694179,41.242681,46.412652,378.087714,9.572641,3.122495,4.839458,0.070864,1,2.199877
2,C57BL6J-2.036,cellina,astrocyte_Fiber_tracts,50,0.344730,0.494441,0.38,0.894737,0.34,0.74,0.623076,32.876234,34.669748,420.287482,5.953089,3.567336,119.274025,0.022515,1,10.921265
3,C57BL6J-2.036,cellina,astrocyte_Isocortex,50,0.893878,0.891688,0.58,1.000000,0.58,0.96,0.550894,37.883680,37.036945,318.547528,6.952761,3.508972,9.688178,0.016515,1,3.112584
4,C57BL6J-2.036,cellina,endothelial cell_Fiber_tracts,50,0.719856,0.992141,0.14,1.000000,0.14,0.82,0.972162,33.310241,34.033472,246.914185,6.105460,3.591354,286.794281,0.007785,1,16.935002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,C57BL6J-2.041,scgen,endothelial cell_Isocortex,50,0.858151,0.934829,0.64,1.000000,0.64,0.98,0.374996,6.402929,7.898638,1185.376782,1.769371,3.305470,39.299080,0.361857,0,6.268898
266,C57BL6J-2.041,scgen,glutamatergic neuron_Fiber_tracts,50,0.403217,0.415690,0.02,1.000000,0.02,0.52,0.965197,13.167032,22.611930,799.425940,10.959205,3.955815,15.894767,0.233393,0,3.986824
267,C57BL6J-2.041,scgen,glutamatergic neuron_Isocortex,50,0.673277,0.913155,0.14,1.000000,0.14,1.00,0.697197,12.993423,23.504357,806.083441,12.112056,4.100569,18.135880,0.257770,0,4.258624
268,C57BL6J-2.041,scgen,oligodendrocyte_Fiber_tracts,50,0.181945,0.753568,0.16,1.000000,0.16,0.94,0.367380,3.948505,5.395181,1350.764502,1.546562,3.577204,12.069176,0.345561,0,3.474072
269,C57BL6J-2.041,scgen,oligodendrocyte_Isocortex,50,0.296038,0.538566,0.02,1.000000,0.02,0.92,0.608762,5.446368,7.442995,687.597986,2.188051,3.670903,195.306519,0.270106,0,13.975211

In [53]:
# Rename holdout_celltype by replacing the last '_' in with '-'
if dataset_name == "merfish":
    combined_df["holdout_celltype"] = combined_df["holdout_celltype"].str.replace("Fiber_tracts", "Fiber-tracts", regex=False)
else:
    combined_df["holdout_celltype"] = combined_df["holdout_celltype"].str.replace("T_cell", "T-cell", regex=False)

In [54]:
# Split holdout_celltype on '_' and place everything in [0] as holdout_celltype, and everything in [1:] as perturbation
combined_df["perturbation"] = combined_df["holdout_celltype"].apply(lambda x: "".join(x.split("_")[-1]) if len(x.split("_")) > 1 else "")
combined_df["holdout_celltype"] = combined_df["holdout_celltype"].apply(lambda x: "-".join(x.split("_")[:-1]))
combined_df

,sid,model_name,holdout_celltype,n_deg,spearman,pearson,precision,direction_match,signed_precision,direction_match_gt,...,edistance_global,edistance_local,edistance_pca,e-distance,rmse,mse_lfc,nb_deviance,seed,rmse_lfc,perturbation
0,C57BL6J-2.036,cellina,GABAergic neuron,50,0.903001,0.916574,0.68,1.000000,0.68,0.98,...,36.511606,42.586272,605.825317,7.898999,2.932238,10.265101,0.029604,1,3.203920,Fiber-tracts
1,C57BL6J-2.036,cellina,GABAergic neuron,50,0.936903,0.974602,0.66,1.000000,0.66,1.00,...,41.242681,46.412652,378.087714,9.572641,3.122495,4.839458,0.070864,1,2.199877,Isocortex
2,C57BL6J-2.036,cellina,astrocyte,50,0.344730,0.494441,0.38,0.894737,0.34,0.74,...,32.876234,34.669748,420.287482,5.953089,3.567336,119.274025,0.022515,1,10.921265,Fiber-tracts
3,C57BL6J-2.036,cellina,astrocyte,50,0.893878,0.891688,0.58,1.000000,0.58,0.96,...,37.883680,37.036945,318.547528,6.952761,3.508972,9.688178,0.016515,1,3.112584,Isocortex
4,C57BL6J-2.036,cellina,endothelial cell,50,0.719856,0.992141,0.14,1.000000,0.14,0.82,...,33.310241,34.033472,246.914185,6.105460,3.591354,286.794281,0.007785,1,16.935002,Fiber-tracts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,C57BL6J-2.041,scgen,endothelial cell,50,0.858151,0.934829,0.64,1.000000,0.64,0.98,...,6.402929,7.898638,1185.376782,1.769371,3.305470,39.299080,0.361857,0,6.268898,Isocortex
266,C57BL6J-2.041,scgen,glutamatergic neuron,50,0.403217,0.415690,0.02,1.000000,0.02,0.52,...,13.167032,22.611930,799.425940,10.959205,3.955815,15.894767,0.233393,0,3.986824,Fiber-tracts
267,C57BL6J-2.041,scgen,glutamatergic neuron,50,0.673277,0.913155,0.14,1.000000,0.14,1.00,...,12.993423,23.504357,806.083441,12.112056,4.100569,18.135880,0.257770,0,4.258624,Isocortex
268,C57BL6J-2.041,scgen,oligodendrocyte,50,0.181945,0.753568,0.16,1.000000,0.16,0.94,...,3.948505,5.395181,1350.764502,1.546562,3.577204,12.069176,0.345561,0,3.474072,Fiber-tracts
269,C57BL6J-2.041,scgen,oligodendrocyte,50,0.296038,0.538566,0.02,1.000000,0.02,0.92,...,5.446368,7.442995,687.597986,2.188051,3.670903,195.306519,0.270106,0,13.975211,Isocortex

In [58]:
metrics = ["pearson", "spearman", "signed_precision", "rmse_lfc"]

In [59]:
# Make a df from combined_df which averages over celltype, sid and perturbation but keeps model_name and seed separate
combined_df_avg_seed = combined_df.groupby(["model_name", "seed"])[metrics].mean().reset_index()
combined_df_avg_seed = combined_df_avg_seed.round(2)
combined_df_avg_seed
# Compute mean and std of each metric for each model across seeds
combined_df_seed_summary = combined_df_avg_seed.groupby("model_name")[metrics].agg(["mean", "std"]).reset_index()
combined_df_seed_summary = combined_df_seed_summary.round(2)
combined_df_seed_summary

  model_name pearson       spearman       signed_precision       rmse_lfc  \
                mean   std     mean   std             mean   std     mean
0    cellina    0.84  0.00     0.73  0.00             0.52  0.01     6.08
1        cpa    0.82  0.00     0.70  0.01             0.44  0.00     6.36
2      scgen    0.77  0.01     0.63  0.00             0.21  0.02     6.47


    std
0  0.04
1  0.01
2  0.02

## Seed-to-seed reliability of cellina

For each metric, decompose cellina's total variance across the 30 (slide, held-out celltype) folds × 3 seeds into a fold (subject) component and a seed (rater) component, using a two-way random-effects ANOVA. Report the intraclass correlation ICC(2,1) — absolute agreement across seeds — with a bootstrap 95% CI, plus the % of total variance attributable to seed identity. ICC(2,1) close to 1 (equivalently, % variance from seed close to 0) means fold identity explains nearly all the variability and the specific random seed used has a negligible effect. Conventionally, ICC > 0.9 is considered "excellent" reliability (Koo & Li, 2016).

In [57]:
def variance_decomposition(wide):
    """Two-way random-effects ANOVA variance decomposition and ICC(2,1).
    wide: DataFrame, rows = subjects (folds), columns = raters (seeds)."""
    X = wide.to_numpy(dtype=float)
    n, k = X.shape
    grand_mean = X.mean()
    row_means = X.mean(axis=1)
    col_means = X.mean(axis=0)

    ss_total = ((X - grand_mean) ** 2).sum()
    ss_rows = k * ((row_means - grand_mean) ** 2).sum()
    ss_cols = n * ((col_means - grand_mean) ** 2).sum()
    ss_error = ss_total - ss_rows - ss_cols

    ms_rows = ss_rows / (n - 1)
    ms_cols = ss_cols / (k - 1)
    ms_error = ss_error / ((n - 1) * (k - 1))

    icc = (ms_rows - ms_error) / (ms_rows + (k - 1) * ms_error + (k / n) * (ms_cols - ms_error))

    var_fold = max((ms_rows - ms_error) / k, 0.0)
    var_seed = max((ms_cols - ms_error) / n, 0.0)
    var_error = max(ms_error, 0.0)
    total_var = var_fold + var_seed + var_error

    return {
        "icc": icc,
        "pct_var_fold": 100 * var_fold / total_var,
        "pct_var_seed": 100 * var_seed / total_var,
        "pct_var_error": 100 * var_error / total_var,
    }

def bootstrap_icc_ci(wide, n_boot=2000, seed=0):
    rng = np.random.default_rng(seed)
    n = len(wide)
    values = []
    for _ in range(n_boot):
        boot = wide.iloc[rng.integers(0, n, n)]
        icc = variance_decomposition(boot)["icc"]
        if np.isfinite(icc):
            values.append(icc)
    return np.percentile(values, [2.5, 97.5])

cellina_df = combined_df[combined_df.model_name == "cellina"].copy()
cellina_df["seed"] = cellina_df["seed"].astype(str)
fold_keys = ["sid", "holdout_celltype", "perturbation"]

rows = []
for metric in metrics:
    wide = cellina_df.pivot_table(index=fold_keys, columns="seed", values=metric)
    result = variance_decomposition(wide)
    ci_low, ci_high = bootstrap_icc_ci(wide)
    rows.append({
        "metric": metric,
        "n_folds": wide.shape[0],
        "n_seeds": wide.shape[1],
        "icc": result["icc"],
        "icc_ci_low": ci_low,
        "icc_ci_high": ci_high,
        "pct_var_fold": result["pct_var_fold"],
        "pct_var_seed": result["pct_var_seed"],
        "pct_var_error": result["pct_var_error"],
    })

icc_df = pd.DataFrame(rows).set_index("metric").round(3)
icc_df

,n_folds,n_seeds,icc,icc_ci_low,icc_ci_high,pct_var_fold,pct_var_seed,pct_var_error
metric,,,,,,,,
pearson,30,3,0.997,0.994,0.998,99.690,0.004,0.307
signed_precision,30,3,0.926,0.824,0.970,92.646,0.151,7.203
e-distance,30,3,0.561,0.266,0.795,55.582,0.000,44.418
rmse_lfc,30,3,0.998,0.996,0.999,99.838,0.001,0.161