# In-vivo multi-seed summary

Loads the per-seed result CSVs produced by `scripts/invivo_multi_seed.py`
(`results/invivo_multiseed_{cellina,cellina-gat,spatialprop}.csv`) and reports
mean ± std **over seeds** for each (model, type, baseline), analogous to the
single-run `summary_fmt` table in `pfish_analysis.ipynb` §4.3.

Note: the `mean` baseline is model-agnostic (no model calls at all) and is only
ever saved under `model == 'cellina'` by the training script, so it appears once
in this summary rather than once per model.

In [1]:
import glob
import os

import numpy as np
import pandas as pd

RESULTS_DIR = "../../results"
METRICS = ["Pearson", "Precision", "E-distance", "RMSE_LFC"]

## Load and combine

In [2]:
csv_paths = sorted(glob.glob(os.path.join(RESULTS_DIR, "invivo_multiseed_*.csv")))
print("found:\n " + "\n ".join(csv_paths))

df = pd.concat([pd.read_csv(p) for p in csv_paths], ignore_index=True)
print(f"\n{len(df)} rows | models: {sorted(df['baseline'].unique())}")
df.groupby("baseline")["seed"].nunique().rename("n_seeds").to_frame()

found:
 ../../results/invivo_multiseed_cellina-gat.csv
 ../../results/invivo_multiseed_cellina.csv
 ../../results/invivo_multiseed_spatialprop.csv

630 rows | models: ['Cellina-GAT', 'Cellina-GAT-random', 'Cellina-base', 'Cellina-base-random', 'SpatialProp', 'SpatialProp-random', 'mean']

                     n_seeds
baseline
Cellina-GAT                5
Cellina-GAT-random         5
Cellina-base               5
Cellina-base-random        5
SpatialProp                5
SpatialProp-random         5
mean                       5

In [3]:
df

,KO,type,baseline,Pearson,Precision,E-distance,RMSE_LFC,seed,model
0,MAP2K2,full,Cellina-GAT,0.913684,1.00,4.636881,0.592517,0,cellina-gat
1,MAP2K2,KO-specific,Cellina-GAT,0.855055,1.00,4.635025,0.517639,0,cellina-gat
2,IRAK1,full,Cellina-GAT,0.757247,0.90,5.324999,0.492173,0,cellina-gat
3,IRAK1,KO-specific,Cellina-GAT,0.898475,1.00,5.382664,0.240796,0,cellina-gat
4,IRF7,full,Cellina-GAT,0.892914,0.90,4.653573,0.262913,0,cellina-gat
...,...,...,...,...,...,...,...,...,...
625,NFKBIA,KO-specific,SpatialProp-random,0.194379,0.60,7.381838,0.738638,4,spatialprop
626,LBP,full,SpatialProp-random,-0.015190,0.48,7.809245,0.705565,4,spatialprop
627,LBP,KO-specific,SpatialProp-random,0.148365,0.70,7.827798,0.474777,4,spatialprop
628,MAP2K3,full,SpatialProp-random,-0.022054,0.30,7.385160,0.873767,4,spatialprop
629,MAP2K3,KO-specific,SpatialProp-random,-0.200269,0.52,7.395256,0.708643,4,spatialprop

## Per-seed summary

Average each metric over the 9 KOs within a (model, seed, type, baseline) --
one score per training run, the same quantity `pfish_analysis.ipynb`'s single-run
`summary_fmt` reports (just not yet aggregated across seeds).

In [4]:
per_seed = df.groupby(["seed", "type", "baseline"])[METRICS].mean().reset_index()
per_seed

,seed,type,baseline,Pearson,Precision,E-distance,RMSE_LFC
0,0,KO-specific,Cellina-GAT,0.307786,0.655556,4.782727,0.395104
1,0,KO-specific,Cellina-GAT-random,0.042270,0.475556,4.749449,0.424641
2,0,KO-specific,Cellina-base,0.311139,0.711111,3.893387,0.413531
3,0,KO-specific,Cellina-base-random,0.028063,0.488889,3.841831,0.427254
4,0,KO-specific,SpatialProp,0.193953,0.622222,7.462140,0.590956
...,...,...,...,...,...,...,...
65,4,full,Cellina-base,0.476337,0.733333,4.316787,0.502346
66,4,full,Cellina-base-random,0.113003,0.571111,4.295702,0.587719
67,4,full,SpatialProp,0.057080,0.544444,7.449240,0.741008
68,4,full,SpatialProp-random,0.001612,0.508889,7.449390,0.764045
69,4,full,mean,0.416440,0.633333,0.121714,0.555013

## Summary: mean ± std over seeds

In [5]:
# numeric mean/std, for programmatic use
summary = per_seed.groupby(["type", "baseline"])[METRICS].agg(["mean", "std"])
summary

                                  Pearson           Precision            \
                                     mean       std      mean       std
type        baseline
KO-specific Cellina-GAT          0.402032  0.066406  0.655556  0.028328
            Cellina-GAT-random   0.067039  0.031783  0.507111  0.031246
            Cellina-base         0.325105  0.084850  0.677778  0.030429
            Cellina-base-random -0.001643  0.052959  0.483111  0.035784
            SpatialProp          0.157013  0.058304  0.553333  0.064502
            SpatialProp-random   0.107952  0.049187  0.522222  0.060103
            mean                 0.057844  0.062096  0.513333  0.034605
full        Cellina-GAT          0.554047  0.096818  0.755556  0.047791
            Cellina-GAT-random   0.139491  0.301587  0.551556  0.124200
            Cellina-base         0.532982  0.050007  0.760000  0.027889
            Cellina-base-random  0.112281  0.234712  0.552000  0.055768
            SpatialProp          0.260795  0.158920  0.613333  0.080277
            SpatialProp-random   0.194597  0.165737  0.578667  0.094341
            mean                 0.506392  0.127449  0.726667  0.077619

                                E-distance            RMSE_LFC
                                      mean       std      mean       std
type        baseline
KO-specific Cellina-GAT           4.892126  0.191250  0.409460  0.013561
            Cellina-GAT-random    4.878822  0.193891  0.460574  0.026251
            Cellina-base          4.125661  0.154940  0.432576  0.012062
            Cellina-base-random   4.126172  0.179961  0.469366  0.029045
            SpatialProp           7.440094  0.035459  0.641832  0.040702
            SpatialProp-random    7.483979  0.019528  0.662955  0.037157
            mean                  0.127943  0.006909  0.461127  0.023426
full        Cellina-GAT           4.874644  0.216314  0.496142  0.027902
            Cellina-GAT-random    4.876723  0.184165  0.586950  0.033246
            Cellina-base          4.141763  0.163417  0.496071  0.018788
            Cellina-base-random   4.118914  0.179094  0.587756  0.030776
            SpatialProp           7.454111  0.024091  0.682143  0.085501
            SpatialProp-random    7.469573  0.017814  0.703670  0.087957
            mean                  0.132157  0.009170  0.536585  0.029357

In [6]:
n_seeds = per_seed.groupby(["type", "baseline"])["seed"].nunique().rename("n_seeds")

summary_fmt = per_seed.groupby(["type", "baseline"])[METRICS].agg(
    lambda x: f"{x.mean():.2f} \u00b1 {x.std():.2f}"
)
summary_fmt = summary_fmt.join(n_seeds)
summary_fmt

                                      Pearson    Precision   E-distance  \
type        baseline
KO-specific Cellina-GAT           0.40 ± 0.07  0.66 ± 0.03  4.89 ± 0.19
            Cellina-GAT-random    0.07 ± 0.03  0.51 ± 0.03  4.88 ± 0.19
            Cellina-base          0.33 ± 0.08  0.68 ± 0.03  4.13 ± 0.15
            Cellina-base-random  -0.00 ± 0.05  0.48 ± 0.04  4.13 ± 0.18
            SpatialProp           0.16 ± 0.06  0.55 ± 0.06  7.44 ± 0.04
            SpatialProp-random    0.11 ± 0.05  0.52 ± 0.06  7.48 ± 0.02
            mean                  0.06 ± 0.06  0.51 ± 0.03  0.13 ± 0.01
full        Cellina-GAT           0.55 ± 0.10  0.76 ± 0.05  4.87 ± 0.22
            Cellina-GAT-random    0.14 ± 0.30  0.55 ± 0.12  4.88 ± 0.18
            Cellina-base          0.53 ± 0.05  0.76 ± 0.03  4.14 ± 0.16
            Cellina-base-random   0.11 ± 0.23  0.55 ± 0.06  4.12 ± 0.18
            SpatialProp           0.26 ± 0.16  0.61 ± 0.08  7.45 ± 0.02
            SpatialProp-random    0.19 ± 0.17  0.58 ± 0.09  7.47 ± 0.02
            mean                  0.51 ± 0.13  0.73 ± 0.08  0.13 ± 0.01

                                    RMSE_LFC  n_seeds
type        baseline
KO-specific Cellina-GAT          0.41 ± 0.01        5
            Cellina-GAT-random   0.46 ± 0.03        5
            Cellina-base         0.43 ± 0.01        5
            Cellina-base-random  0.47 ± 0.03        5
            SpatialProp          0.64 ± 0.04        5
            SpatialProp-random   0.66 ± 0.04        5
            mean                 0.46 ± 0.02        5
full        Cellina-GAT          0.50 ± 0.03        5
            Cellina-GAT-random   0.59 ± 0.03        5
            Cellina-base         0.50 ± 0.02        5
            Cellina-base-random  0.59 ± 0.03        5
            SpatialProp          0.68 ± 0.09        5
            SpatialProp-random   0.70 ± 0.09        5
            mean                 0.54 ± 0.03        5

## LaTeX table

Writes the manuscript-format table (`type` × `method` rows, Pearson/Precision/E-distance/
RMSE_LFC columns, mean ± std over seeds, best value per column **within each type section**
bolded) to `results/invivo_summary_table.tex`. Row order and which baseline maps to which
display name are fixed below; a baseline not in that mapping (e.g. a new model) still prints,
under its raw name, appended after the known rows -- so nothing silently goes missing.

In [7]:
TEX_PATH = os.path.join(RESULTS_DIR, "invivo_summary_table.tex")

METRIC_BETTER = {"Pearson": "max", "Precision": "max", "E-distance": "min", "RMSE_LFC": "min"}

LATEX_HEADER = (r"Type & Method & Pearson $\uparrow$ & Precision$_{\mathrm{signed}}$ $\uparrow$ "
                 r"& E-distance $\downarrow$ & RMSE\textsubscript{LFC} $\downarrow$ \\")

TYPE_SECTIONS = [("KO-specific", "KO-specific"), ("full", "Full")]

# baseline (as written by scripts/invivo_multi_seed.py) -> display name in the table
FIXED_METHOD_NAMES = {
    "Cellina-base": "Cellina",
    "Cellina-GAT": "Cellina-GAT",
    "SpatialProp": "SpatialProp",
    "mean": "Mean shift",
    "Cellina-base-random": "Cellina-rand",
    "Cellina-GAT-random": "Cellina-GAT-rand",
    "SpatialProp-random": "SpatialProp-rand",
}
# fixed row order (only rows actually present in the data are emitted, so the \multirow count
# below is never stale even as models get added/removed)
LATEX_METHOD_ORDER = ["Cellina", "Cellina-GAT", "SpatialProp", "Mean shift",
                       "Cellina-rand", "Cellina-GAT-rand", "SpatialProp-rand",
                       "TERRA-LoRA", "TERRA-LoRA-rand"]


def method_name(baseline):
    if baseline in FIXED_METHOD_NAMES:
        return FIXED_METHOD_NAMES[baseline]
    if baseline.startswith("terra-lora-ep"):  # embeds the LoRA epoch, e.g. terra-lora-ep5(-random)
        return "TERRA-LoRA-rand" if baseline.endswith("-random") else "TERRA-LoRA"
    return baseline  # unknown baseline: still shown, just unmapped and sorted to the end


def make_latex_table(summary, metrics=METRICS):
    tbl = summary.reset_index()
    baseline_col = tbl[("baseline", "")] if ("baseline", "") in tbl.columns else tbl["baseline"]
    type_col = tbl[("type", "")] if ("type", "") in tbl.columns else tbl["type"]
    tbl["Method"] = [method_name(b) for b in baseline_col]
    tbl["_type"] = type_col.values

    lines = [r"\begin{tabular}{llcccc}", r"\toprule", LATEX_HEADER, r"\midrule"]
    for type_val, type_label in TYPE_SECTIONS:
        sub = tbl[tbl["_type"] == type_val].set_index("Method")
        row_order = [m for m in LATEX_METHOD_ORDER if m in sub.index]
        row_order += [m for m in sub.index if m not in LATEX_METHOD_ORDER]  # unmapped, appended
        sub = sub.loc[row_order]
        if sub.empty:
            continue

        best = {m: (sub[(m, "mean")].idxmax() if METRIC_BETTER[m] == "max" else sub[(m, "mean")].idxmin())
                for m in metrics}

        n = len(sub)
        lines.append(r"\multirow{%d}{*}{\shortstack{KO-\\specific}}" % n
                     if type_val == "KO-specific" else type_label)
        for method, row in sub.iterrows():
            cells = []
            for metric in metrics:
                s = f"{row[(metric, 'mean')]:.2f} $\\pm$ {row[(metric, 'std')]:.2f}"
                if best[metric] == method:
                    s = r"\textbf{%s}" % s
                cells.append(s)
            lines.append("& " + method + " & " + " & ".join(cells) + r" \\")
        lines.append(r"\midrule")

    lines[-1] = r"\bottomrule"  # overwrite the last section's trailing \midrule
    lines.append(r"\end{tabular}")
    return "\n".join(lines)


tex = make_latex_table(summary)
with open(TEX_PATH, "w") as f:
    f.write(tex + "\n")
print(f"wrote {TEX_PATH}\n")
print(tex)

wrote ../../results/invivo_summary_table.tex

\begin{tabular}{llcccc}
\toprule
Type & Method & Pearson $\uparrow$ & Precision$_{\mathrm{signed}}$ $\uparrow$ & E-distance $\downarrow$ & RMSE\textsubscript{LFC} $\downarrow$ \\
\midrule
\multirow{7}{*}{\shortstack{KO-\\specific}}
& Cellina & 0.33 $\pm$ 0.08 & \textbf{0.68 $\pm$ 0.03} & 4.13 $\pm$ 0.15 & 0.43 $\pm$ 0.01 \\
& Cellina-GAT & \textbf{0.40 $\pm$ 0.07} & 0.66 $\pm$ 0.03 & 4.89 $\pm$ 0.19 & \textbf{0.41 $\pm$ 0.01} \\
& SpatialProp & 0.16 $\pm$ 0.06 & 0.55 $\pm$ 0.06 & 7.44 $\pm$ 0.04 & 0.64 $\pm$ 0.04 \\
& Mean shift & 0.06 $\pm$ 0.06 & 0.51 $\pm$ 0.03 & \textbf{0.13 $\pm$ 0.01} & 0.46 $\pm$ 0.02 \\
& Cellina-rand & -0.00 $\pm$ 0.05 & 0.48 $\pm$ 0.04 & 4.13 $\pm$ 0.18 & 0.47 $\pm$ 0.03 \\
& Cellina-GAT-rand & 0.07 $\pm$ 0.03 & 0.51 $\pm$ 0.03 & 4.88 $\pm$ 0.19 & 0.46 $\pm$ 0.03 \\
& SpatialProp-rand & 0.11 $\pm$ 0.05 & 0.52 $\pm$ 0.06 & 7.48 $\pm$ 0.02 & 0.66 $\pm$ 0.04 \\
\midrule
Full
& Cellina & 0.53 $\pm$ 0.05 & \textbf{0.76 $\pm$ 0.03} & 4.14 $\pm$ 0.16 & \textbf{0.50 $\pm$ 0.02} \\
& Cellina-GAT & \textbf{0.55 $\pm$ 0.10} & 0.76 $\pm$ 0.05 & 4.87 $\pm$ 0.22 & 0.50 $\pm$ 0.03 \\
& SpatialProp & 0.26 $\pm$ 0.16 & 0.61 $\pm$ 0.08 & 7.45 $\pm$ 0.02 & 0.68 $\pm$ 0.09 \\
& Mean shift & 0.51 $\pm$ 0.13 & 0.73 $\pm$ 0.08 & \textbf{0.13 $\pm$ 0.01} & 0.54 $\pm$ 0.03 \\
& Cellina-rand & 0.11 $\pm$ 0.23 & 0.55 $\pm$ 0.06 & 4.12 $\pm$ 0.18 & 0.59 $\pm$ 0.03 \\
& Cellina-GAT-rand & 0.14 $\pm$ 0.30 & 0.55 $\pm$ 0.12 & 4.88 $\pm$ 0.18 & 0.59 $\pm$ 0.03 \\
& SpatialProp-rand & 0.19 $\pm$ 0.17 & 0.58 $\pm$ 0.09 & 7.47 $\pm$ 0.02 & 0.70 $\pm$ 0.09 \\
\bottomrule
\end{tabular}